// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetTimesheetSetupsParams,
  GetWorkspaceTimesheetsHandlerParams,
  ModelsTimeEntry,
  TimesheetsAPITimesheet,
  TimesheetsGetPaginatedResponse,
  TimesheetsPostTimesheetHoursPayload,
  TimesheetsPutBatchTimesheetPayload,
  TimesheetsPutTimesheetPayload,
  TimesheetsTimesheetHoursResponse,
  TimesheetsetupsAPITimesheetSetup,
  TimesheetsetupsCreatePayload,
  TimesheetsetupsGetPaginatedResponse,
  TimesheetsetupsUpdatePayload
} from './togglAPI.schemas';

import { togglAxios } from '../mutators/toggl';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get timesheet setups for a given workspace.
 * @summary Get timesheet setups
 */
export const getTimesheetSetups = (
    workspaceId: number,
    params?: GetTimesheetSetupsParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<TimesheetsetupsGetPaginatedResponse>(
      {url: `/workspaces/${workspaceId}/timesheet_setups`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetTimesheetSetupsQueryKey = (workspaceId?: number,
    params?: GetTimesheetSetupsParams,) => {
    return [
    `/workspaces/${workspaceId}/timesheet_setups`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTimesheetSetupsQueryOptions = <TData = Awaited<ReturnType<typeof getTimesheetSetups>>, TError = string | string | string | string>(workspaceId: number,
    params?: GetTimesheetSetupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimesheetSetups>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTimesheetSetupsQueryKey(workspaceId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTimesheetSetups>>> = ({ signal }) => getTimesheetSetups(workspaceId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTimesheetSetups>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetTimesheetSetupsQueryResult = NonNullable<Awaited<ReturnType<typeof getTimesheetSetups>>>
export type GetTimesheetSetupsQueryError = string | string | string | string


export function useGetTimesheetSetups<TData = Awaited<ReturnType<typeof getTimesheetSetups>>, TError = string | string | string | string>(
 workspaceId: number,
    params: undefined |  GetTimesheetSetupsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimesheetSetups>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTimesheetSetups>>,
          TError,
          Awaited<ReturnType<typeof getTimesheetSetups>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTimesheetSetups<TData = Awaited<ReturnType<typeof getTimesheetSetups>>, TError = string | string | string | string>(
 workspaceId: number,
    params?: GetTimesheetSetupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimesheetSetups>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTimesheetSetups>>,
          TError,
          Awaited<ReturnType<typeof getTimesheetSetups>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetTimesheetSetups<TData = Awaited<ReturnType<typeof getTimesheetSetups>>, TError = string | string | string | string>(
 workspaceId: number,
    params?: GetTimesheetSetupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimesheetSetups>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get timesheet setups
 */

export function useGetTimesheetSetups<TData = Awaited<ReturnType<typeof getTimesheetSetups>>, TError = string | string | string | string>(
 workspaceId: number,
    params?: GetTimesheetSetupsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimesheetSetups>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetTimesheetSetupsQueryOptions(workspaceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create timesheet setups.
 * @summary Create a timesheet setup
 */
export const postTimesheetSetups = (
    workspaceId: number,
    timesheetsetupsCreatePayload: TimesheetsetupsCreatePayload,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<TimesheetsetupsAPITimesheetSetup[]>(
      {url: `/workspaces/${workspaceId}/timesheet_setups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: timesheetsetupsCreatePayload, signal
    },
      options);
    }
  


export const getPostTimesheetSetupsMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTimesheetSetups>>, TError,{workspaceId: number;data: TimesheetsetupsCreatePayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postTimesheetSetups>>, TError,{workspaceId: number;data: TimesheetsetupsCreatePayload}, TContext> => {

const mutationKey = ['postTimesheetSetups'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTimesheetSetups>>, {workspaceId: number;data: TimesheetsetupsCreatePayload}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postTimesheetSetups(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostTimesheetSetupsMutationResult = NonNullable<Awaited<ReturnType<typeof postTimesheetSetups>>>
    export type PostTimesheetSetupsMutationBody = TimesheetsetupsCreatePayload
    export type PostTimesheetSetupsMutationError = string | string | string | string

    /**
 * @summary Create a timesheet setup
 */
export const usePostTimesheetSetups = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTimesheetSetups>>, TError,{workspaceId: number;data: TimesheetsetupsCreatePayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postTimesheetSetups>>,
        TError,
        {workspaceId: number;data: TimesheetsetupsCreatePayload},
        TContext
      > => {

      const mutationOptions = getPostTimesheetSetupsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Updates a timesheet setups.
 * @summary Update a timesheet setup
 */
export const putTimesheetSetups = (
    workspaceId: number,
    setupId: number,
    timesheetsetupsUpdatePayload: TimesheetsetupsUpdatePayload,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<TimesheetsetupsAPITimesheetSetup>(
      {url: `/workspaces/${workspaceId}/timesheet_setups/${setupId}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: timesheetsetupsUpdatePayload, signal
    },
      options);
    }
  


export const getPutTimesheetSetupsMutationOptions = <TError = string | string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTimesheetSetups>>, TError,{workspaceId: number;setupId: number;data: TimesheetsetupsUpdatePayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof putTimesheetSetups>>, TError,{workspaceId: number;setupId: number;data: TimesheetsetupsUpdatePayload}, TContext> => {

const mutationKey = ['putTimesheetSetups'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putTimesheetSetups>>, {workspaceId: number;setupId: number;data: TimesheetsetupsUpdatePayload}> = (props) => {
          const {workspaceId,setupId,data} = props ?? {};

          return  putTimesheetSetups(workspaceId,setupId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutTimesheetSetupsMutationResult = NonNullable<Awaited<ReturnType<typeof putTimesheetSetups>>>
    export type PutTimesheetSetupsMutationBody = TimesheetsetupsUpdatePayload
    export type PutTimesheetSetupsMutationError = string | string | string | string | string

    /**
 * @summary Update a timesheet setup
 */
export const usePutTimesheetSetups = <TError = string | string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putTimesheetSetups>>, TError,{workspaceId: number;setupId: number;data: TimesheetsetupsUpdatePayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putTimesheetSetups>>,
        TError,
        {workspaceId: number;setupId: number;data: TimesheetsetupsUpdatePayload},
        TContext
      > => {

      const mutationOptions = getPutTimesheetSetupsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a timesheet setup for a given workspace.
 * @summary Delete a timesheet setup
 */
export const deleteTimesheetSetups = (
    workspaceId: number,
    setupId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<string>(
      {url: `/workspaces/${workspaceId}/timesheet_setups/${setupId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteTimesheetSetupsMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTimesheetSetups>>, TError,{workspaceId: number;setupId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTimesheetSetups>>, TError,{workspaceId: number;setupId: number}, TContext> => {

const mutationKey = ['deleteTimesheetSetups'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTimesheetSetups>>, {workspaceId: number;setupId: number}> = (props) => {
          const {workspaceId,setupId} = props ?? {};

          return  deleteTimesheetSetups(workspaceId,setupId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTimesheetSetupsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTimesheetSetups>>>
    
    export type DeleteTimesheetSetupsMutationError = string | string | string | string

    /**
 * @summary Delete a timesheet setup
 */
export const useDeleteTimesheetSetups = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTimesheetSetups>>, TError,{workspaceId: number;setupId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTimesheetSetups>>,
        TError,
        {workspaceId: number;setupId: number},
        TContext
      > => {

      const mutationOptions = getDeleteTimesheetSetupsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get timesheets applying various filters.
 * @summary Get timesheets
 */
export const getWorkspaceTimesheetsHandler = (
    workspaceId: number,
    params?: GetWorkspaceTimesheetsHandlerParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<TimesheetsGetPaginatedResponse[]>(
      {url: `/workspaces/${workspaceId}/timesheets`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetWorkspaceTimesheetsHandlerQueryKey = (workspaceId?: number,
    params?: GetWorkspaceTimesheetsHandlerParams,) => {
    return [
    `/workspaces/${workspaceId}/timesheets`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetWorkspaceTimesheetsHandlerQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>, TError = string | string | string | string>(workspaceId: number,
    params?: GetWorkspaceTimesheetsHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspaceTimesheetsHandlerQueryKey(workspaceId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>> = ({ signal }) => getWorkspaceTimesheetsHandler(workspaceId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWorkspaceTimesheetsHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>>
export type GetWorkspaceTimesheetsHandlerQueryError = string | string | string | string


export function useGetWorkspaceTimesheetsHandler<TData = Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>, TError = string | string | string | string>(
 workspaceId: number,
    params: undefined |  GetWorkspaceTimesheetsHandlerParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceTimesheetsHandler<TData = Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>, TError = string | string | string | string>(
 workspaceId: number,
    params?: GetWorkspaceTimesheetsHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceTimesheetsHandler<TData = Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>, TError = string | string | string | string>(
 workspaceId: number,
    params?: GetWorkspaceTimesheetsHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get timesheets
 */

export function useGetWorkspaceTimesheetsHandler<TData = Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>, TError = string | string | string | string>(
 workspaceId: number,
    params?: GetWorkspaceTimesheetsHandlerParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetsHandler>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWorkspaceTimesheetsHandlerQueryOptions(workspaceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Updates a batch of timesheets.
 * @summary Update a batch of timesheets
 */
export const putWorkspaceTimesheets = (
    workspaceId: number,
    timesheetsPutBatchTimesheetPayload: TimesheetsPutBatchTimesheetPayload,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<TimesheetsAPITimesheet>(
      {url: `/workspaces/${workspaceId}/timesheets`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: timesheetsPutBatchTimesheetPayload
    },
      options);
    }
  


export const getPutWorkspaceTimesheetsMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceTimesheets>>, TError,{workspaceId: number;data: TimesheetsPutBatchTimesheetPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceTimesheets>>, TError,{workspaceId: number;data: TimesheetsPutBatchTimesheetPayload}, TContext> => {

const mutationKey = ['putWorkspaceTimesheets'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putWorkspaceTimesheets>>, {workspaceId: number;data: TimesheetsPutBatchTimesheetPayload}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  putWorkspaceTimesheets(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutWorkspaceTimesheetsMutationResult = NonNullable<Awaited<ReturnType<typeof putWorkspaceTimesheets>>>
    export type PutWorkspaceTimesheetsMutationBody = TimesheetsPutBatchTimesheetPayload
    export type PutWorkspaceTimesheetsMutationError = string | string | string | string

    /**
 * @summary Update a batch of timesheets
 */
export const usePutWorkspaceTimesheets = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceTimesheets>>, TError,{workspaceId: number;data: TimesheetsPutBatchTimesheetPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putWorkspaceTimesheets>>,
        TError,
        {workspaceId: number;data: TimesheetsPutBatchTimesheetPayload},
        TContext
      > => {

      const mutationOptions = getPutWorkspaceTimesheetsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get timesheet working hours and total tracked seconds.
 * @summary Get timesheets hours
 */
export const getWorkspaceTimesheetHoursHandler = (
    workspaceId: number,
    timesheetsPostTimesheetHoursPayload: TimesheetsPostTimesheetHoursPayload,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<TimesheetsTimesheetHoursResponse[]>(
      {url: `/workspaces/${workspaceId}/timesheets/hours`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: timesheetsPostTimesheetHoursPayload, signal
    },
      options);
    }
  


export const getGetWorkspaceTimesheetHoursHandlerMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetHoursHandler>>, TError,{workspaceId: number;data: TimesheetsPostTimesheetHoursPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetHoursHandler>>, TError,{workspaceId: number;data: TimesheetsPostTimesheetHoursPayload}, TContext> => {

const mutationKey = ['getWorkspaceTimesheetHoursHandler'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getWorkspaceTimesheetHoursHandler>>, {workspaceId: number;data: TimesheetsPostTimesheetHoursPayload}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  getWorkspaceTimesheetHoursHandler(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetWorkspaceTimesheetHoursHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceTimesheetHoursHandler>>>
    export type GetWorkspaceTimesheetHoursHandlerMutationBody = TimesheetsPostTimesheetHoursPayload
    export type GetWorkspaceTimesheetHoursHandlerMutationError = string | string | string | string

    /**
 * @summary Get timesheets hours
 */
export const useGetWorkspaceTimesheetHoursHandler = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetHoursHandler>>, TError,{workspaceId: number;data: TimesheetsPostTimesheetHoursPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getWorkspaceTimesheetHoursHandler>>,
        TError,
        {workspaceId: number;data: TimesheetsPostTimesheetHoursPayload},
        TContext
      > => {

      const mutationOptions = getGetWorkspaceTimesheetHoursHandlerMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Updates a timesheet.
 * @summary Update timesheets
 */
export const putWorkspaceTimesheet = (
    workspaceId: number,
    setupId: number,
    startDate: string,
    timesheetsPutTimesheetPayload: TimesheetsPutTimesheetPayload,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<TimesheetsAPITimesheet>(
      {url: `/workspaces/${workspaceId}/timesheets/${setupId}/${startDate}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: timesheetsPutTimesheetPayload
    },
      options);
    }
  


export const getPutWorkspaceTimesheetMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceTimesheet>>, TError,{workspaceId: number;setupId: number;startDate: string;data: TimesheetsPutTimesheetPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceTimesheet>>, TError,{workspaceId: number;setupId: number;startDate: string;data: TimesheetsPutTimesheetPayload}, TContext> => {

const mutationKey = ['putWorkspaceTimesheet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putWorkspaceTimesheet>>, {workspaceId: number;setupId: number;startDate: string;data: TimesheetsPutTimesheetPayload}> = (props) => {
          const {workspaceId,setupId,startDate,data} = props ?? {};

          return  putWorkspaceTimesheet(workspaceId,setupId,startDate,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutWorkspaceTimesheetMutationResult = NonNullable<Awaited<ReturnType<typeof putWorkspaceTimesheet>>>
    export type PutWorkspaceTimesheetMutationBody = TimesheetsPutTimesheetPayload
    export type PutWorkspaceTimesheetMutationError = string | string | string | string

    /**
 * @summary Update timesheets
 */
export const usePutWorkspaceTimesheet = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceTimesheet>>, TError,{workspaceId: number;setupId: number;startDate: string;data: TimesheetsPutTimesheetPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putWorkspaceTimesheet>>,
        TError,
        {workspaceId: number;setupId: number;startDate: string;data: TimesheetsPutTimesheetPayload},
        TContext
      > => {

      const mutationOptions = getPutWorkspaceTimesheetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get the time entries from within a timesheet timeframe.
 * @summary Get timesheet time entries
 */
export const getWorkspaceTimesheetTimeEntriesHandler = (
    workspaceId: number,
    setupId: number,
    startDate: string,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsTimeEntry[]>(
      {url: `/workspaces/${workspaceId}/timesheets/${setupId}/${startDate}/time_entries`, method: 'GET', signal
    },
      options);
    }
  



export const getGetWorkspaceTimesheetTimeEntriesHandlerQueryKey = (workspaceId?: number,
    setupId?: number,
    startDate?: string,) => {
    return [
    `/workspaces/${workspaceId}/timesheets/${setupId}/${startDate}/time_entries`
    ] as const;
    }

    
export const getGetWorkspaceTimesheetTimeEntriesHandlerQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>, TError = string | string | string | string>(workspaceId: number,
    setupId: number,
    startDate: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspaceTimesheetTimeEntriesHandlerQueryKey(workspaceId,setupId,startDate);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>> = ({ signal }) => getWorkspaceTimesheetTimeEntriesHandler(workspaceId,setupId,startDate, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId && setupId && startDate), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWorkspaceTimesheetTimeEntriesHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>>
export type GetWorkspaceTimesheetTimeEntriesHandlerQueryError = string | string | string | string


export function useGetWorkspaceTimesheetTimeEntriesHandler<TData = Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>, TError = string | string | string | string>(
 workspaceId: number,
    setupId: number,
    startDate: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceTimesheetTimeEntriesHandler<TData = Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>, TError = string | string | string | string>(
 workspaceId: number,
    setupId: number,
    startDate: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceTimesheetTimeEntriesHandler<TData = Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>, TError = string | string | string | string>(
 workspaceId: number,
    setupId: number,
    startDate: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get timesheet time entries
 */

export function useGetWorkspaceTimesheetTimeEntriesHandler<TData = Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>, TError = string | string | string | string>(
 workspaceId: number,
    setupId: number,
    startDate: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTimesheetTimeEntriesHandler>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWorkspaceTimesheetTimeEntriesHandlerQueryOptions(workspaceId,setupId,startDate,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



