// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AccountsLinkedSsoProfile,
  GetSaml2LoginUrlParams,
  PostSaml2CallbackBody,
  Saml2LoginResponse,
  SsoConfirmation
} from './togglAPI.schemas';

import { togglAxios } from '../mutators/toggl';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the SSO URL given an email address for authenticating in an Identity Provider.
 * @summary SAML2 Identity Provider URL
 */
export const getSaml2LoginUrl = (
    params: GetSaml2LoginUrlParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<Saml2LoginResponse>(
      {url: `/auth/saml2/login`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetSaml2LoginUrlQueryKey = (params?: GetSaml2LoginUrlParams,) => {
    return [
    `/auth/saml2/login`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetSaml2LoginUrlQueryOptions = <TData = Awaited<ReturnType<typeof getSaml2LoginUrl>>, TError = string | string>(params: GetSaml2LoginUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaml2LoginUrl>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSaml2LoginUrlQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSaml2LoginUrl>>> = ({ signal }) => getSaml2LoginUrl(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSaml2LoginUrl>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetSaml2LoginUrlQueryResult = NonNullable<Awaited<ReturnType<typeof getSaml2LoginUrl>>>
export type GetSaml2LoginUrlQueryError = string | string


export function useGetSaml2LoginUrl<TData = Awaited<ReturnType<typeof getSaml2LoginUrl>>, TError = string | string>(
 params: GetSaml2LoginUrlParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaml2LoginUrl>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaml2LoginUrl>>,
          TError,
          Awaited<ReturnType<typeof getSaml2LoginUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSaml2LoginUrl<TData = Awaited<ReturnType<typeof getSaml2LoginUrl>>, TError = string | string>(
 params: GetSaml2LoginUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaml2LoginUrl>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSaml2LoginUrl>>,
          TError,
          Awaited<ReturnType<typeof getSaml2LoginUrl>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetSaml2LoginUrl<TData = Awaited<ReturnType<typeof getSaml2LoginUrl>>, TError = string | string>(
 params: GetSaml2LoginUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaml2LoginUrl>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary SAML2 Identity Provider URL
 */

export function useGetSaml2LoginUrl<TData = Awaited<ReturnType<typeof getSaml2LoginUrl>>, TError = string | string>(
 params: GetSaml2LoginUrlParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSaml2LoginUrl>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetSaml2LoginUrlQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Receives the IdP Callback containing the SAML2 assertion with response of user authentication in the IdP.
 * @summary SAML2 Identity Provider Callback
 */
export const postSaml2Callback = (
    workspaceId: number,
    postSaml2CallbackBody: PostSaml2CallbackBody,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`SAMLResponse`, postSaml2CallbackBody.SAMLResponse)
if(postSaml2CallbackBody.RelayState !== undefined) {
 formUrlEncoded.append(`RelayState`, postSaml2CallbackBody.RelayState)
 }

      return togglAxios<unknown>(
      {url: `/auth/saml2/login/${workspaceId}`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      options);
    }
  


export const getPostSaml2CallbackMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSaml2Callback>>, TError,{workspaceId: number;data: PostSaml2CallbackBody}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postSaml2Callback>>, TError,{workspaceId: number;data: PostSaml2CallbackBody}, TContext> => {

const mutationKey = ['postSaml2Callback'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSaml2Callback>>, {workspaceId: number;data: PostSaml2CallbackBody}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postSaml2Callback(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostSaml2CallbackMutationResult = NonNullable<Awaited<ReturnType<typeof postSaml2Callback>>>
    export type PostSaml2CallbackMutationBody = PostSaml2CallbackBody
    export type PostSaml2CallbackMutationError = string | string

    /**
 * @summary SAML2 Identity Provider Callback
 */
export const usePostSaml2Callback = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSaml2Callback>>, TError,{workspaceId: number;data: PostSaml2CallbackBody}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSaml2Callback>>,
        TError,
        {workspaceId: number;data: PostSaml2CallbackBody},
        TContext
      > => {

      const mutationOptions = getPostSaml2CallbackMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Confirm SSO enabling in existing Toggl account after successful SSO
 * @summary Confirm SSO enabling for user account
 */
export const postEnableSso = (
    ssoConfirmation: SsoConfirmation,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/me/enable_sso`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ssoConfirmation, signal
    },
      options);
    }
  


export const getPostEnableSsoMutationOptions = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEnableSso>>, TError,{data: SsoConfirmation}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postEnableSso>>, TError,{data: SsoConfirmation}, TContext> => {

const mutationKey = ['postEnableSso'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postEnableSso>>, {data: SsoConfirmation}> = (props) => {
          const {data} = props ?? {};

          return  postEnableSso(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostEnableSsoMutationResult = NonNullable<Awaited<ReturnType<typeof postEnableSso>>>
    export type PostEnableSsoMutationBody = SsoConfirmation
    export type PostEnableSsoMutationError = string

    /**
 * @summary Confirm SSO enabling for user account
 */
export const usePostEnableSso = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postEnableSso>>, TError,{data: SsoConfirmation}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postEnableSso>>,
        TError,
        {data: SsoConfirmation},
        TContext
      > => {

      const mutationOptions = getPostEnableSsoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Resets API token for the current user.
 * @summary ResetToken
 */
export const postResetToken = (
    
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/me/reset_token`, method: 'POST', signal
    },
      options);
    }
  


export const getPostResetTokenMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postResetToken>>, TError,void, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postResetToken>>, TError,void, TContext> => {

const mutationKey = ['postResetToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postResetToken>>, void> = () => {
          

          return  postResetToken(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostResetTokenMutationResult = NonNullable<Awaited<ReturnType<typeof postResetToken>>>
    
    export type PostResetTokenMutationError = string | string

    /**
 * @summary ResetToken
 */
export const usePostResetToken = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postResetToken>>, TError,void, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postResetToken>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostResetTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns a list of SSO profiles that are linked to the given workspace.
 * @summary Get linked SSO profiles for a workspace
 */
export const getWorkspaceSso = (
    workspaceId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<AccountsLinkedSsoProfile[]>(
      {url: `/workspaces/${workspaceId}/linked_sso_profiles`, method: 'GET', signal
    },
      options);
    }
  



export const getGetWorkspaceSsoQueryKey = (workspaceId?: number,) => {
    return [
    `/workspaces/${workspaceId}/linked_sso_profiles`
    ] as const;
    }

    
export const getGetWorkspaceSsoQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspaceSso>>, TError = string>(workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceSso>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspaceSsoQueryKey(workspaceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspaceSso>>> = ({ signal }) => getWorkspaceSso(workspaceId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceSso>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWorkspaceSsoQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceSso>>>
export type GetWorkspaceSsoQueryError = string


export function useGetWorkspaceSso<TData = Awaited<ReturnType<typeof getWorkspaceSso>>, TError = string>(
 workspaceId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceSso>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceSso>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceSso>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceSso<TData = Awaited<ReturnType<typeof getWorkspaceSso>>, TError = string>(
 workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceSso>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceSso>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceSso>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceSso<TData = Awaited<ReturnType<typeof getWorkspaceSso>>, TError = string>(
 workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceSso>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get linked SSO profiles for a workspace
 */

export function useGetWorkspaceSso<TData = Awaited<ReturnType<typeof getWorkspaceSso>>, TError = string>(
 workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceSso>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWorkspaceSsoQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Link the workspace with the given ID to an SSO profile with the given ID.
 * @summary Link SSO profile to a workspace
 */
export const putWorkspaceSso = (
    workspaceId: number,
    ssoProfileId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<AccountsLinkedSsoProfile[]>(
      {url: `/workspaces/${workspaceId}/linked_sso_profiles/${ssoProfileId}`, method: 'PUT'
    },
      options);
    }
  


export const getPutWorkspaceSsoMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceSso>>, TError,{workspaceId: number;ssoProfileId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceSso>>, TError,{workspaceId: number;ssoProfileId: number}, TContext> => {

const mutationKey = ['putWorkspaceSso'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putWorkspaceSso>>, {workspaceId: number;ssoProfileId: number}> = (props) => {
          const {workspaceId,ssoProfileId} = props ?? {};

          return  putWorkspaceSso(workspaceId,ssoProfileId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutWorkspaceSsoMutationResult = NonNullable<Awaited<ReturnType<typeof putWorkspaceSso>>>
    
    export type PutWorkspaceSsoMutationError = string | string | string

    /**
 * @summary Link SSO profile to a workspace
 */
export const usePutWorkspaceSso = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceSso>>, TError,{workspaceId: number;ssoProfileId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putWorkspaceSso>>,
        TError,
        {workspaceId: number;ssoProfileId: number},
        TContext
      > => {

      const mutationOptions = getPutWorkspaceSsoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Unlink the workspace from an SSO profile.
 * @summary Unlink the workspace from an SSO profile.
 */
export const deleteWorkspaceLinkedSsoProfiles = (
    workspaceId: number,
    ssoProfileId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<AccountsLinkedSsoProfile[]>(
      {url: `/workspaces/${workspaceId}/linked_sso_profiles/${ssoProfileId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteWorkspaceLinkedSsoProfilesMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceLinkedSsoProfiles>>, TError,{workspaceId: number;ssoProfileId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceLinkedSsoProfiles>>, TError,{workspaceId: number;ssoProfileId: number}, TContext> => {

const mutationKey = ['deleteWorkspaceLinkedSsoProfiles'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkspaceLinkedSsoProfiles>>, {workspaceId: number;ssoProfileId: number}> = (props) => {
          const {workspaceId,ssoProfileId} = props ?? {};

          return  deleteWorkspaceLinkedSsoProfiles(workspaceId,ssoProfileId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkspaceLinkedSsoProfilesMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspaceLinkedSsoProfiles>>>
    
    export type DeleteWorkspaceLinkedSsoProfilesMutationError = string | string | string

    /**
 * @summary Unlink the workspace from an SSO profile.
 */
export const useDeleteWorkspaceLinkedSsoProfiles = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceLinkedSsoProfiles>>, TError,{workspaceId: number;ssoProfileId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWorkspaceLinkedSsoProfiles>>,
        TError,
        {workspaceId: number;ssoProfileId: number},
        TContext
      > => {

      const mutationOptions = getDeleteWorkspaceLinkedSsoProfilesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    