// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DesktopLoginToken
} from './togglAPI.schemas';

import { togglAxios } from '../mutators/toggl';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Store new desktop login token
 * @summary Get desktop login token
 */
export const getDesktopLogin = (
    
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<unknown>(
      {url: `/desktop_login`, method: 'GET', signal
    },
      options);
    }
  



export const getGetDesktopLoginQueryKey = () => {
    return [
    `/desktop_login`
    ] as const;
    }

    
export const getGetDesktopLoginQueryOptions = <TData = Awaited<ReturnType<typeof getDesktopLogin>>, TError = string | string>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDesktopLogin>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDesktopLoginQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDesktopLogin>>> = ({ signal }) => getDesktopLogin(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDesktopLogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetDesktopLoginQueryResult = NonNullable<Awaited<ReturnType<typeof getDesktopLogin>>>
export type GetDesktopLoginQueryError = string | string


export function useGetDesktopLogin<TData = Awaited<ReturnType<typeof getDesktopLogin>>, TError = string | string>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDesktopLogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDesktopLogin>>,
          TError,
          Awaited<ReturnType<typeof getDesktopLogin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetDesktopLogin<TData = Awaited<ReturnType<typeof getDesktopLogin>>, TError = string | string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDesktopLogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDesktopLogin>>,
          TError,
          Awaited<ReturnType<typeof getDesktopLogin>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetDesktopLogin<TData = Awaited<ReturnType<typeof getDesktopLogin>>, TError = string | string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDesktopLogin>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get desktop login token
 */

export function useGetDesktopLogin<TData = Awaited<ReturnType<typeof getDesktopLogin>>, TError = string | string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDesktopLogin>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetDesktopLoginQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Store new desktop login token
 * @summary Post desktop login token
 */
export const postDesktopLoginTokens = (
    
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<DesktopLoginToken>(
      {url: `/desktop_login_tokens`, method: 'POST', signal
    },
      options);
    }
  


export const getPostDesktopLoginTokensMutationOptions = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDesktopLoginTokens>>, TError,void, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postDesktopLoginTokens>>, TError,void, TContext> => {

const mutationKey = ['postDesktopLoginTokens'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postDesktopLoginTokens>>, void> = () => {
          

          return  postDesktopLoginTokens(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostDesktopLoginTokensMutationResult = NonNullable<Awaited<ReturnType<typeof postDesktopLoginTokens>>>
    
    export type PostDesktopLoginTokensMutationError = string

    /**
 * @summary Post desktop login token
 */
export const usePostDesktopLoginTokens = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postDesktopLoginTokens>>, TError,void, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postDesktopLoginTokens>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostDesktopLoginTokensMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    