// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BetafeaturesAlphaFeatureAddInputData,
  BetafeaturesAlphaFeatureRolloutInputData,
  BetafeaturesBetaFeatureRolloutRollbackInputData
} from './togglAPI.schemas.js';

import { togglAxios } from '../mutators/toggl.js';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Creates a new beta feature
 * @summary Creates a new beta feature
 */
export const addBetaFeature = (
    betafeaturesAlphaFeatureAddInputData: BetafeaturesAlphaFeatureAddInputData,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/beta_features`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: betafeaturesAlphaFeatureAddInputData, signal
    },
      options);
    }
  


export const getAddBetaFeatureMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addBetaFeature>>, TError,{data: BetafeaturesAlphaFeatureAddInputData}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof addBetaFeature>>, TError,{data: BetafeaturesAlphaFeatureAddInputData}, TContext> => {

const mutationKey = ['addBetaFeature'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addBetaFeature>>, {data: BetafeaturesAlphaFeatureAddInputData}> = (props) => {
          const {data} = props ?? {};

          return  addBetaFeature(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddBetaFeatureMutationResult = NonNullable<Awaited<ReturnType<typeof addBetaFeature>>>
    export type AddBetaFeatureMutationBody = BetafeaturesAlphaFeatureAddInputData
    export type AddBetaFeatureMutationError = void

    /**
 * @summary Creates a new beta feature
 */
export const useAddBetaFeature = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addBetaFeature>>, TError,{data: BetafeaturesAlphaFeatureAddInputData}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addBetaFeature>>,
        TError,
        {data: BetafeaturesAlphaFeatureAddInputData},
        TContext
      > => {

      const mutationOptions = getAddBetaFeatureMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates rollout job
 * @summary Creates rollout job
 */
export const createRolloutJob = (
    betaFeatureId: number,
    betafeaturesAlphaFeatureRolloutInputData: BetafeaturesAlphaFeatureRolloutInputData,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/beta_features/${betaFeatureId}/rollout/scheduled_job`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: betafeaturesAlphaFeatureRolloutInputData, signal
    },
      options);
    }
  


export const getCreateRolloutJobMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRolloutJob>>, TError,{betaFeatureId: number;data: BetafeaturesAlphaFeatureRolloutInputData}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof createRolloutJob>>, TError,{betaFeatureId: number;data: BetafeaturesAlphaFeatureRolloutInputData}, TContext> => {

const mutationKey = ['createRolloutJob'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRolloutJob>>, {betaFeatureId: number;data: BetafeaturesAlphaFeatureRolloutInputData}> = (props) => {
          const {betaFeatureId,data} = props ?? {};

          return  createRolloutJob(betaFeatureId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateRolloutJobMutationResult = NonNullable<Awaited<ReturnType<typeof createRolloutJob>>>
    export type CreateRolloutJobMutationBody = BetafeaturesAlphaFeatureRolloutInputData
    export type CreateRolloutJobMutationError = void

    /**
 * @summary Creates rollout job
 */
export const useCreateRolloutJob = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRolloutJob>>, TError,{betaFeatureId: number;data: BetafeaturesAlphaFeatureRolloutInputData}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRolloutJob>>,
        TError,
        {betaFeatureId: number;data: BetafeaturesAlphaFeatureRolloutInputData},
        TContext
      > => {

      const mutationOptions = getCreateRolloutJobMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete rollout job
 * @summary Deletes rollout job
 */
export const deleteRolloutJob = (
    betaFeatureId: number,
    scheduledJobId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<string>(
      {url: `/beta_features/${betaFeatureId}/rollout/scheduled_job/${scheduledJobId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteRolloutJobMutationOptions = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRolloutJob>>, TError,{betaFeatureId: number;scheduledJobId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRolloutJob>>, TError,{betaFeatureId: number;scheduledJobId: number}, TContext> => {

const mutationKey = ['deleteRolloutJob'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRolloutJob>>, {betaFeatureId: number;scheduledJobId: number}> = (props) => {
          const {betaFeatureId,scheduledJobId} = props ?? {};

          return  deleteRolloutJob(betaFeatureId,scheduledJobId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteRolloutJobMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRolloutJob>>>
    
    export type DeleteRolloutJobMutationError = void | void

    /**
 * @summary Deletes rollout job
 */
export const useDeleteRolloutJob = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRolloutJob>>, TError,{betaFeatureId: number;scheduledJobId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRolloutJob>>,
        TError,
        {betaFeatureId: number;scheduledJobId: number},
        TContext
      > => {

      const mutationOptions = getDeleteRolloutJobMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Rolls back rollout job
 * @summary Rolls back rollout job
 */
export const rollbackBetaFeatureRollout = (
    betaFeatureId: number,
    rolloutId: number,
    betafeaturesBetaFeatureRolloutRollbackInputData: BetafeaturesBetaFeatureRolloutRollbackInputData,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/beta_features/${betaFeatureId}/rollout/${rolloutId}/rollback`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: betafeaturesBetaFeatureRolloutRollbackInputData, signal
    },
      options);
    }
  


export const getRollbackBetaFeatureRolloutMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rollbackBetaFeatureRollout>>, TError,{betaFeatureId: number;rolloutId: number;data: BetafeaturesBetaFeatureRolloutRollbackInputData}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof rollbackBetaFeatureRollout>>, TError,{betaFeatureId: number;rolloutId: number;data: BetafeaturesBetaFeatureRolloutRollbackInputData}, TContext> => {

const mutationKey = ['rollbackBetaFeatureRollout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof rollbackBetaFeatureRollout>>, {betaFeatureId: number;rolloutId: number;data: BetafeaturesBetaFeatureRolloutRollbackInputData}> = (props) => {
          const {betaFeatureId,rolloutId,data} = props ?? {};

          return  rollbackBetaFeatureRollout(betaFeatureId,rolloutId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RollbackBetaFeatureRolloutMutationResult = NonNullable<Awaited<ReturnType<typeof rollbackBetaFeatureRollout>>>
    export type RollbackBetaFeatureRolloutMutationBody = BetafeaturesBetaFeatureRolloutRollbackInputData
    export type RollbackBetaFeatureRolloutMutationError = void

    /**
 * @summary Rolls back rollout job
 */
export const useRollbackBetaFeatureRollout = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof rollbackBetaFeatureRollout>>, TError,{betaFeatureId: number;rolloutId: number;data: BetafeaturesBetaFeatureRolloutRollbackInputData}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof rollbackBetaFeatureRollout>>,
        TError,
        {betaFeatureId: number;rolloutId: number;data: BetafeaturesBetaFeatureRolloutRollbackInputData},
        TContext
      > => {

      const mutationOptions = getRollbackBetaFeatureRolloutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    