// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetIntegrationsCalendarCalendarsSelectedParams,
  GetIntegrationsCalendarCallbackProviderParams,
  GetIntegrationsCalendarEventsParams,
  GetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsParams,
  GetIntegrationsCalendarIntegrationIdCalendarsParams,
  GetIntegrationsCalendarSetupParams,
  HandlercalendarCalendarsResponse,
  HandlercalendarEventsResponse,
  HandlercalendarFetchedCalendarsResponse,
  HandlercalendarPatchCalendar,
  HandlercalendarPostDetailsSuggestionRequest,
  HandlercalendarPostDetailsSuggestionResponse,
  HandlercalendarResponse,
  ModelsCalendar,
  ModelsIntegration,
  ModelsSuggestion
} from './togglAPI.schemas';

import { togglAxios } from '../mutators/toggl';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get all integrations a user has. Each user may have at most one integration per provider.
 * @summary Get all integrations a user has.
 */
export const getIntegrationsCalendar = (
    
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsIntegration[]>(
      {url: `/integrations/calendar`, method: 'GET', signal
    },
      options);
    }
  



export const getGetIntegrationsCalendarQueryKey = () => {
    return [
    `/integrations/calendar`
    ] as const;
    }

    
export const getGetIntegrationsCalendarQueryOptions = <TData = Awaited<ReturnType<typeof getIntegrationsCalendar>>, TError = string>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendar>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIntegrationsCalendarQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIntegrationsCalendar>>> = ({ signal }) => getIntegrationsCalendar(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendar>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIntegrationsCalendarQueryResult = NonNullable<Awaited<ReturnType<typeof getIntegrationsCalendar>>>
export type GetIntegrationsCalendarQueryError = string


export function useGetIntegrationsCalendar<TData = Awaited<ReturnType<typeof getIntegrationsCalendar>>, TError = string>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendar>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendar>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendar<TData = Awaited<ReturnType<typeof getIntegrationsCalendar>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendar>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendar>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendar>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendar<TData = Awaited<ReturnType<typeof getIntegrationsCalendar>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendar>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get all integrations a user has.
 */

export function useGetIntegrationsCalendar<TData = Awaited<ReturnType<typeof getIntegrationsCalendar>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendar>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIntegrationsCalendarQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get all calendars for a given user that was previously saved in the database.
 * @summary Get all calendars for a given user.
 */
export const getIntegrationsCalendarCalendarsSelected = (
    params?: GetIntegrationsCalendarCalendarsSelectedParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<HandlercalendarCalendarsResponse>(
      {url: `/integrations/calendar/calendars/selected`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetIntegrationsCalendarCalendarsSelectedQueryKey = (params?: GetIntegrationsCalendarCalendarsSelectedParams,) => {
    return [
    `/integrations/calendar/calendars/selected`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetIntegrationsCalendarCalendarsSelectedQueryOptions = <TData = Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>, TError = string | string>(params?: GetIntegrationsCalendarCalendarsSelectedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIntegrationsCalendarCalendarsSelectedQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>> = ({ signal }) => getIntegrationsCalendarCalendarsSelected(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIntegrationsCalendarCalendarsSelectedQueryResult = NonNullable<Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>>
export type GetIntegrationsCalendarCalendarsSelectedQueryError = string | string


export function useGetIntegrationsCalendarCalendarsSelected<TData = Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>, TError = string | string>(
 params: undefined |  GetIntegrationsCalendarCalendarsSelectedParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarCalendarsSelected<TData = Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>, TError = string | string>(
 params?: GetIntegrationsCalendarCalendarsSelectedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarCalendarsSelected<TData = Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>, TError = string | string>(
 params?: GetIntegrationsCalendarCalendarsSelectedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get all calendars for a given user.
 */

export function useGetIntegrationsCalendarCalendarsSelected<TData = Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>, TError = string | string>(
 params?: GetIntegrationsCalendarCalendarsSelectedParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCalendarsSelected>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIntegrationsCalendarCalendarsSelectedQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Callback endpoint used only by the Calendar Service Provider, which fetches the code
 * @summary Callback for provider OAuth setup.
 */
export const getIntegrationsCalendarCallbackProvider = (
    provider: string,
    params: GetIntegrationsCalendarCallbackProviderParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<unknown>(
      {url: `/integrations/calendar/callback/${provider}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetIntegrationsCalendarCallbackProviderQueryKey = (provider?: string,
    params?: GetIntegrationsCalendarCallbackProviderParams,) => {
    return [
    `/integrations/calendar/callback/${provider}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetIntegrationsCalendarCallbackProviderQueryOptions = <TData = Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>, TError = string | string>(provider: string,
    params: GetIntegrationsCalendarCallbackProviderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIntegrationsCalendarCallbackProviderQueryKey(provider,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>> = ({ signal }) => getIntegrationsCalendarCallbackProvider(provider,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(provider), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIntegrationsCalendarCallbackProviderQueryResult = NonNullable<Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>>
export type GetIntegrationsCalendarCallbackProviderQueryError = string | string


export function useGetIntegrationsCalendarCallbackProvider<TData = Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>, TError = string | string>(
 provider: string,
    params: GetIntegrationsCalendarCallbackProviderParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarCallbackProvider<TData = Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>, TError = string | string>(
 provider: string,
    params: GetIntegrationsCalendarCallbackProviderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarCallbackProvider<TData = Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>, TError = string | string>(
 provider: string,
    params: GetIntegrationsCalendarCallbackProviderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Callback for provider OAuth setup.
 */

export function useGetIntegrationsCalendarCallbackProvider<TData = Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>, TError = string | string>(
 provider: string,
    params: GetIntegrationsCalendarCallbackProviderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarCallbackProvider>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIntegrationsCalendarCallbackProviderQueryOptions(provider,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Get all events from selected calendars for the caller user. This endpoint will only return events if events were fetched from provider before the request is made. Check which is the endpoint for the events.
 * @summary Get all events for the caller user.
 */
export const getIntegrationsCalendarEvents = (
    params: GetIntegrationsCalendarEventsParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<HandlercalendarEventsResponse>(
      {url: `/integrations/calendar/events`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetIntegrationsCalendarEventsQueryKey = (params?: GetIntegrationsCalendarEventsParams,) => {
    return [
    `/integrations/calendar/events`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetIntegrationsCalendarEventsQueryOptions = <TData = Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>, TError = string | string>(params: GetIntegrationsCalendarEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIntegrationsCalendarEventsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>> = ({ signal }) => getIntegrationsCalendarEvents(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIntegrationsCalendarEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>>
export type GetIntegrationsCalendarEventsQueryError = string | string


export function useGetIntegrationsCalendarEvents<TData = Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>, TError = string | string>(
 params: GetIntegrationsCalendarEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarEvents<TData = Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>, TError = string | string>(
 params: GetIntegrationsCalendarEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarEvents<TData = Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>, TError = string | string>(
 params: GetIntegrationsCalendarEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get all events for the caller user.
 */

export function useGetIntegrationsCalendarEvents<TData = Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>, TError = string | string>(
 params: GetIntegrationsCalendarEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEvents>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIntegrationsCalendarEventsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Given one or more event IDs, this endpoint responds with the most probable event details
(and its accuracy) to assign to the to-be-created time entry for each event ID.
This endpoint will only suggests time entries with description and project not empty, because it uses
the description to tell if the TE is similar and the project as the main detail to be suggested.

If the description is equal, as well as all the other details, the accuracy will be 100%, in the case
the description is equal but the other details differs, the most frequent will be suggested and the
accuracy will be given based on the frequency. In the case there is no TE with the same description
the most similar will be suggested based on the Jaro-Winkler algorithm, and the accuracy will be the
similarity rating.

This endpoint returns status 200 OK with only the successful suggestions. Any event ID that is invalid
or the user does not have access to will be ignored, as well as any event that has no available suggestion.
 * @summary Get details suggestion for given events.
 */
export const postIntegrationsCalendarEventsDetailsSuggestion = (
    handlercalendarPostDetailsSuggestionRequest: HandlercalendarPostDetailsSuggestionRequest,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<HandlercalendarPostDetailsSuggestionResponse>(
      {url: `/integrations/calendar/events/details-suggestion`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: handlercalendarPostDetailsSuggestionRequest, signal
    },
      options);
    }
  


export const getPostIntegrationsCalendarEventsDetailsSuggestionMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postIntegrationsCalendarEventsDetailsSuggestion>>, TError,{data: HandlercalendarPostDetailsSuggestionRequest}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postIntegrationsCalendarEventsDetailsSuggestion>>, TError,{data: HandlercalendarPostDetailsSuggestionRequest}, TContext> => {

const mutationKey = ['postIntegrationsCalendarEventsDetailsSuggestion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postIntegrationsCalendarEventsDetailsSuggestion>>, {data: HandlercalendarPostDetailsSuggestionRequest}> = (props) => {
          const {data} = props ?? {};

          return  postIntegrationsCalendarEventsDetailsSuggestion(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostIntegrationsCalendarEventsDetailsSuggestionMutationResult = NonNullable<Awaited<ReturnType<typeof postIntegrationsCalendarEventsDetailsSuggestion>>>
    export type PostIntegrationsCalendarEventsDetailsSuggestionMutationBody = HandlercalendarPostDetailsSuggestionRequest
    export type PostIntegrationsCalendarEventsDetailsSuggestionMutationError = string | string

    /**
 * @summary Get details suggestion for given events.
 */
export const usePostIntegrationsCalendarEventsDetailsSuggestion = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postIntegrationsCalendarEventsDetailsSuggestion>>, TError,{data: HandlercalendarPostDetailsSuggestionRequest}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postIntegrationsCalendarEventsDetailsSuggestion>>,
        TError,
        {data: HandlercalendarPostDetailsSuggestionRequest},
        TContext
      > => {

      const mutationOptions = getPostIntegrationsCalendarEventsDetailsSuggestionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Fetch all events from a user's selected calendars and save in database.
 * @summary Update all events from selected calendars for a user.
 */
export const postIntegrationsCalendarEventsUpdate = (
    
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<HandlercalendarResponse>(
      {url: `/integrations/calendar/events/update`, method: 'POST', signal
    },
      options);
    }
  


export const getPostIntegrationsCalendarEventsUpdateMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postIntegrationsCalendarEventsUpdate>>, TError,void, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postIntegrationsCalendarEventsUpdate>>, TError,void, TContext> => {

const mutationKey = ['postIntegrationsCalendarEventsUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postIntegrationsCalendarEventsUpdate>>, void> = () => {
          

          return  postIntegrationsCalendarEventsUpdate(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostIntegrationsCalendarEventsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof postIntegrationsCalendarEventsUpdate>>>
    
    export type PostIntegrationsCalendarEventsUpdateMutationError = string | string | string

    /**
 * @summary Update all events from selected calendars for a user.
 */
export const usePostIntegrationsCalendarEventsUpdate = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postIntegrationsCalendarEventsUpdate>>, TError,void, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postIntegrationsCalendarEventsUpdate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostIntegrationsCalendarEventsUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Given an event ID, this endpoint responds with the most probable event details (and the accuracy) to
assign to the to-be-created time entry.
This endpoint will only suggests time entries with description and project not empty, because it uses the
description to tell if the TE is similar and the project as the main detail to be suggested.

If the description is equal, as well as all the other details, the accuracy will be 100%, in the case
the description is equal but the other details differs, the most frequent will be suggested and the
accuracy will be given based on the frequency. In the case there is no TE with the same description
the most similar will be suggested based on the Jaro-Winkler algorithm, and the accuracy will be the
similarity rating.

This endpoint returns status 200 OK and a "null" string in case no suggestion was found.
 * @summary Get details suggestion for a given event.
 */
export const getIntegrationsCalendarEventsEventIdDetailsSuggestion = (
    eventId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsSuggestion>(
      {url: `/integrations/calendar/events/${eventId}/details-suggestion`, method: 'GET', signal
    },
      options);
    }
  



export const getGetIntegrationsCalendarEventsEventIdDetailsSuggestionQueryKey = (eventId?: number,) => {
    return [
    `/integrations/calendar/events/${eventId}/details-suggestion`
    ] as const;
    }

    
export const getGetIntegrationsCalendarEventsEventIdDetailsSuggestionQueryOptions = <TData = Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>, TError = string | string | string>(eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIntegrationsCalendarEventsEventIdDetailsSuggestionQueryKey(eventId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>> = ({ signal }) => getIntegrationsCalendarEventsEventIdDetailsSuggestion(eventId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(eventId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIntegrationsCalendarEventsEventIdDetailsSuggestionQueryResult = NonNullable<Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>>
export type GetIntegrationsCalendarEventsEventIdDetailsSuggestionQueryError = string | string | string


export function useGetIntegrationsCalendarEventsEventIdDetailsSuggestion<TData = Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>, TError = string | string | string>(
 eventId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarEventsEventIdDetailsSuggestion<TData = Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>, TError = string | string | string>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarEventsEventIdDetailsSuggestion<TData = Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>, TError = string | string | string>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get details suggestion for a given event.
 */

export function useGetIntegrationsCalendarEventsEventIdDetailsSuggestion<TData = Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>, TError = string | string | string>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarEventsEventIdDetailsSuggestion>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIntegrationsCalendarEventsEventIdDetailsSuggestionQueryOptions(eventId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Set up an integration with a given provider, returning a URL to the said provider in order to
 * @summary Get URL for setting up a calendar integration with given provider.
 */
export const getIntegrationsCalendarSetup = (
    params: GetIntegrationsCalendarSetupParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<unknown>(
      {url: `/integrations/calendar/setup`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetIntegrationsCalendarSetupQueryKey = (params?: GetIntegrationsCalendarSetupParams,) => {
    return [
    `/integrations/calendar/setup`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetIntegrationsCalendarSetupQueryOptions = <TData = Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>, TError = string | string | string | string>(params: GetIntegrationsCalendarSetupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIntegrationsCalendarSetupQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>> = ({ signal }) => getIntegrationsCalendarSetup(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIntegrationsCalendarSetupQueryResult = NonNullable<Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>>
export type GetIntegrationsCalendarSetupQueryError = string | string | string | string


export function useGetIntegrationsCalendarSetup<TData = Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>, TError = string | string | string | string>(
 params: GetIntegrationsCalendarSetupParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarSetup<TData = Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>, TError = string | string | string | string>(
 params: GetIntegrationsCalendarSetupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarSetup<TData = Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>, TError = string | string | string | string>(
 params: GetIntegrationsCalendarSetupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get URL for setting up a calendar integration with given provider.
 */

export function useGetIntegrationsCalendarSetup<TData = Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>, TError = string | string | string | string>(
 params: GetIntegrationsCalendarSetupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarSetup>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIntegrationsCalendarSetupQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Updates an integration properties.
 * @summary Update a given integration.
 */
export const putIntegrationsCalendarIntegrationId = (
    integrationId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<string>(
      {url: `/integrations/calendar/${integrationId}`, method: 'PUT'
    },
      options);
    }
  


export const getPutIntegrationsCalendarIntegrationIdMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putIntegrationsCalendarIntegrationId>>, TError,{integrationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof putIntegrationsCalendarIntegrationId>>, TError,{integrationId: number}, TContext> => {

const mutationKey = ['putIntegrationsCalendarIntegrationId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putIntegrationsCalendarIntegrationId>>, {integrationId: number}> = (props) => {
          const {integrationId} = props ?? {};

          return  putIntegrationsCalendarIntegrationId(integrationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutIntegrationsCalendarIntegrationIdMutationResult = NonNullable<Awaited<ReturnType<typeof putIntegrationsCalendarIntegrationId>>>
    
    export type PutIntegrationsCalendarIntegrationIdMutationError = string | string

    /**
 * @summary Update a given integration.
 */
export const usePutIntegrationsCalendarIntegrationId = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putIntegrationsCalendarIntegrationId>>, TError,{integrationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putIntegrationsCalendarIntegrationId>>,
        TError,
        {integrationId: number},
        TContext
      > => {

      const mutationOptions = getPutIntegrationsCalendarIntegrationIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Executes logic deletion of an integration.
 * @summary Delete a given integration.
 */
export const deleteIntegrationsCalendarIntegrationId = (
    integrationId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<string>(
      {url: `/integrations/calendar/${integrationId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteIntegrationsCalendarIntegrationIdMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIntegrationsCalendarIntegrationId>>, TError,{integrationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteIntegrationsCalendarIntegrationId>>, TError,{integrationId: number}, TContext> => {

const mutationKey = ['deleteIntegrationsCalendarIntegrationId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteIntegrationsCalendarIntegrationId>>, {integrationId: number}> = (props) => {
          const {integrationId} = props ?? {};

          return  deleteIntegrationsCalendarIntegrationId(integrationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteIntegrationsCalendarIntegrationIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteIntegrationsCalendarIntegrationId>>>
    
    export type DeleteIntegrationsCalendarIntegrationIdMutationError = string | string

    /**
 * @summary Delete a given integration.
 */
export const useDeleteIntegrationsCalendarIntegrationId = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIntegrationsCalendarIntegrationId>>, TError,{integrationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteIntegrationsCalendarIntegrationId>>,
        TError,
        {integrationId: number},
        TContext
      > => {

      const mutationOptions = getDeleteIntegrationsCalendarIntegrationIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get all calendars for a given integration that was previously saved in the database.
 * @summary Get all calendars for a given integration.
 */
export const getIntegrationsCalendarIntegrationIdCalendars = (
    integrationId: number,
    params?: GetIntegrationsCalendarIntegrationIdCalendarsParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<HandlercalendarCalendarsResponse>(
      {url: `/integrations/calendar/${integrationId}/calendars`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetIntegrationsCalendarIntegrationIdCalendarsQueryKey = (integrationId?: number,
    params?: GetIntegrationsCalendarIntegrationIdCalendarsParams,) => {
    return [
    `/integrations/calendar/${integrationId}/calendars`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetIntegrationsCalendarIntegrationIdCalendarsQueryOptions = <TData = Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>, TError = string | string | string>(integrationId: number,
    params?: GetIntegrationsCalendarIntegrationIdCalendarsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIntegrationsCalendarIntegrationIdCalendarsQueryKey(integrationId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>> = ({ signal }) => getIntegrationsCalendarIntegrationIdCalendars(integrationId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(integrationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIntegrationsCalendarIntegrationIdCalendarsQueryResult = NonNullable<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>>
export type GetIntegrationsCalendarIntegrationIdCalendarsQueryError = string | string | string


export function useGetIntegrationsCalendarIntegrationIdCalendars<TData = Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>, TError = string | string | string>(
 integrationId: number,
    params: undefined |  GetIntegrationsCalendarIntegrationIdCalendarsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarIntegrationIdCalendars<TData = Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>, TError = string | string | string>(
 integrationId: number,
    params?: GetIntegrationsCalendarIntegrationIdCalendarsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarIntegrationIdCalendars<TData = Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>, TError = string | string | string>(
 integrationId: number,
    params?: GetIntegrationsCalendarIntegrationIdCalendarsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get all calendars for a given integration.
 */

export function useGetIntegrationsCalendarIntegrationIdCalendars<TData = Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>, TError = string | string | string>(
 integrationId: number,
    params?: GetIntegrationsCalendarIntegrationIdCalendarsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendars>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIntegrationsCalendarIntegrationIdCalendarsQueryOptions(integrationId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * This endpoint uses the passed integration to get a provider and update all the calendars from that
 * @summary Updates calendar data according to provider API.
 */
export const postIntegrationsCalendarIntegrationIdCalendarsUpdate = (
    integrationId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<HandlercalendarFetchedCalendarsResponse>(
      {url: `/integrations/calendar/${integrationId}/calendars/update`, method: 'POST', signal
    },
      options);
    }
  


export const getPostIntegrationsCalendarIntegrationIdCalendarsUpdateMutationOptions = <TError = string | string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postIntegrationsCalendarIntegrationIdCalendarsUpdate>>, TError,{integrationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postIntegrationsCalendarIntegrationIdCalendarsUpdate>>, TError,{integrationId: number}, TContext> => {

const mutationKey = ['postIntegrationsCalendarIntegrationIdCalendarsUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postIntegrationsCalendarIntegrationIdCalendarsUpdate>>, {integrationId: number}> = (props) => {
          const {integrationId} = props ?? {};

          return  postIntegrationsCalendarIntegrationIdCalendarsUpdate(integrationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostIntegrationsCalendarIntegrationIdCalendarsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof postIntegrationsCalendarIntegrationIdCalendarsUpdate>>>
    
    export type PostIntegrationsCalendarIntegrationIdCalendarsUpdateMutationError = string | string | string | string | string

    /**
 * @summary Updates calendar data according to provider API.
 */
export const usePostIntegrationsCalendarIntegrationIdCalendarsUpdate = <TError = string | string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postIntegrationsCalendarIntegrationIdCalendarsUpdate>>, TError,{integrationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postIntegrationsCalendarIntegrationIdCalendarsUpdate>>,
        TError,
        {integrationId: number},
        TContext
      > => {

      const mutationOptions = getPostIntegrationsCalendarIntegrationIdCalendarsUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * This endpoint is used to set updatable fields of a calendar like selected field.
 * @summary Sets whether a calendar is or not selected by the user.
 */
export const patchIntegrationsCalendarIntegrationIdCalendarsCalendarId = (
    integrationId: number,
    calendarId: number,
    handlercalendarPatchCalendar: HandlercalendarPatchCalendar,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<ModelsCalendar[]>(
      {url: `/integrations/calendar/${integrationId}/calendars/${calendarId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: handlercalendarPatchCalendar
    },
      options);
    }
  


export const getPatchIntegrationsCalendarIntegrationIdCalendarsCalendarIdMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchIntegrationsCalendarIntegrationIdCalendarsCalendarId>>, TError,{integrationId: number;calendarId: number;data: HandlercalendarPatchCalendar}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchIntegrationsCalendarIntegrationIdCalendarsCalendarId>>, TError,{integrationId: number;calendarId: number;data: HandlercalendarPatchCalendar}, TContext> => {

const mutationKey = ['patchIntegrationsCalendarIntegrationIdCalendarsCalendarId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchIntegrationsCalendarIntegrationIdCalendarsCalendarId>>, {integrationId: number;calendarId: number;data: HandlercalendarPatchCalendar}> = (props) => {
          const {integrationId,calendarId,data} = props ?? {};

          return  patchIntegrationsCalendarIntegrationIdCalendarsCalendarId(integrationId,calendarId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchIntegrationsCalendarIntegrationIdCalendarsCalendarIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchIntegrationsCalendarIntegrationIdCalendarsCalendarId>>>
    export type PatchIntegrationsCalendarIntegrationIdCalendarsCalendarIdMutationBody = HandlercalendarPatchCalendar
    export type PatchIntegrationsCalendarIntegrationIdCalendarsCalendarIdMutationError = string | string | string | string

    /**
 * @summary Sets whether a calendar is or not selected by the user.
 */
export const usePatchIntegrationsCalendarIntegrationIdCalendarsCalendarId = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchIntegrationsCalendarIntegrationIdCalendarsCalendarId>>, TError,{integrationId: number;calendarId: number;data: HandlercalendarPatchCalendar}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchIntegrationsCalendarIntegrationIdCalendarsCalendarId>>,
        TError,
        {integrationId: number;calendarId: number;data: HandlercalendarPatchCalendar},
        TContext
      > => {

      const mutationOptions = getPatchIntegrationsCalendarIntegrationIdCalendarsCalendarIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get all events for a given calendar in a given integration.
 * @summary (DEPRECATED) Get all events for a given calendar in a given integration.
 */
export const getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents = (
    integrationId: number,
    idCalendar: string,
    params: GetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<HandlercalendarEventsResponse>(
      {url: `/integrations/calendar/${integrationId}/calendars/${idCalendar}/events`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsQueryKey = (integrationId?: number,
    idCalendar?: string,
    params?: GetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsParams,) => {
    return [
    `/integrations/calendar/${integrationId}/calendars/${idCalendar}/events`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsQueryOptions = <TData = Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>, TError = string | string | string | string | string>(integrationId: number,
    idCalendar: string,
    params: GetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsQueryKey(integrationId,idCalendar,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>> = ({ signal }) => getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents(integrationId,idCalendar,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(integrationId && idCalendar), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>>
export type GetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsQueryError = string | string | string | string | string


export function useGetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents<TData = Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>, TError = string | string | string | string | string>(
 integrationId: number,
    idCalendar: string,
    params: GetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents<TData = Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>, TError = string | string | string | string | string>(
 integrationId: number,
    idCalendar: string,
    params: GetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents<TData = Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>, TError = string | string | string | string | string>(
 integrationId: number,
    idCalendar: string,
    params: GetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary (DEPRECATED) Get all events for a given calendar in a given integration.
 */

export function useGetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents<TData = Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>, TError = string | string | string | string | string>(
 integrationId: number,
    idCalendar: string,
    params: GetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIntegrationsCalendarIntegrationIdCalendarsIdCalendarEvents>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIntegrationsCalendarIntegrationIdCalendarsIdCalendarEventsQueryOptions(integrationId,idCalendar,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



