// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ModelsCountry,
  ModelsSubdivision
} from './togglAPI.schemas.js';

import { togglAxios } from '../mutators/toggl.js';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns a list of existing countries
 * @summary Countries
 */
export const getCountries = (
    
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsCountry[]>(
      {url: `/countries`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCountriesQueryKey = () => {
    return [
    `/countries`
    ] as const;
    }

    
export const getGetCountriesQueryOptions = <TData = Awaited<ReturnType<typeof getCountries>>, TError = string>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountriesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountries>>> = ({ signal }) => getCountries(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCountriesQueryResult = NonNullable<Awaited<ReturnType<typeof getCountries>>>
export type GetCountriesQueryError = string


export function useGetCountries<TData = Awaited<ReturnType<typeof getCountries>>, TError = string>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCountries>>,
          TError,
          Awaited<ReturnType<typeof getCountries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCountries<TData = Awaited<ReturnType<typeof getCountries>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCountries>>,
          TError,
          Awaited<ReturnType<typeof getCountries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCountries<TData = Awaited<ReturnType<typeof getCountries>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Countries
 */

export function useGetCountries<TData = Awaited<ReturnType<typeof getCountries>>, TError = string>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountries>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCountriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Returns a list of subdivisions for a specific country.
 * @summary CountrySubdivisions
 */
export const getCountriesCountryIdSubdivisions = (
    countryId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsSubdivision[]>(
      {url: `/countries/${countryId}/subdivisions`, method: 'GET', signal
    },
      options);
    }
  



export const getGetCountriesCountryIdSubdivisionsQueryKey = (countryId?: number,) => {
    return [
    `/countries/${countryId}/subdivisions`
    ] as const;
    }

    
export const getGetCountriesCountryIdSubdivisionsQueryOptions = <TData = Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>, TError = string | string>(countryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountriesCountryIdSubdivisionsQueryKey(countryId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>> = ({ signal }) => getCountriesCountryIdSubdivisions(countryId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(countryId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCountriesCountryIdSubdivisionsQueryResult = NonNullable<Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>>
export type GetCountriesCountryIdSubdivisionsQueryError = string | string


export function useGetCountriesCountryIdSubdivisions<TData = Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>, TError = string | string>(
 countryId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>,
          TError,
          Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCountriesCountryIdSubdivisions<TData = Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>, TError = string | string>(
 countryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>,
          TError,
          Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCountriesCountryIdSubdivisions<TData = Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>, TError = string | string>(
 countryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary CountrySubdivisions
 */

export function useGetCountriesCountryIdSubdivisions<TData = Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>, TError = string | string>(
 countryId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountriesCountryIdSubdivisions>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCountriesCountryIdSubdivisionsQueryOptions(countryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



