// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PostFeedbackWebBody,
  PostUnifiedFeedbackBody
} from './togglAPI.schemas';

import { togglAxios } from '../mutators/toggl';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Send Feedback
 * @summary Feedback
 */
export const postUnifiedFeedback = (
    postUnifiedFeedbackBody: PostUnifiedFeedbackBody,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`toggl_version`, postUnifiedFeedbackBody.toggl_version)
formUrlEncoded.append(`date`, postUnifiedFeedbackBody.date)
formUrlEncoded.append(`details`, postUnifiedFeedbackBody.details)
if(postUnifiedFeedbackBody.update_channel !== undefined) {
 formUrlEncoded.append(`update_channel`, postUnifiedFeedbackBody.update_channel)
 }
if(postUnifiedFeedbackBody.subject !== undefined) {
 formUrlEncoded.append(`subject`, postUnifiedFeedbackBody.subject)
 }
if(postUnifiedFeedbackBody.device_model !== undefined) {
 formUrlEncoded.append(`device_model`, postUnifiedFeedbackBody.device_model)
 }
if(postUnifiedFeedbackBody.build_number !== undefined) {
 formUrlEncoded.append(`build_number`, postUnifiedFeedbackBody.build_number)
 }
if(postUnifiedFeedbackBody.operating_system !== undefined) {
 formUrlEncoded.append(`operating_system`, postUnifiedFeedbackBody.operating_system)
 }
if(postUnifiedFeedbackBody.latest !== undefined) {
 formUrlEncoded.append(`latest`, postUnifiedFeedbackBody.latest.toString())
 }
if(postUnifiedFeedbackBody.files !== undefined) {
 formUrlEncoded.append(`files`, postUnifiedFeedbackBody.files)
 }

      return togglAxios<void>(
      {url: `/feedback`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      options);
    }
  


export const getPostUnifiedFeedbackMutationOptions = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUnifiedFeedback>>, TError,{data: PostUnifiedFeedbackBody}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postUnifiedFeedback>>, TError,{data: PostUnifiedFeedbackBody}, TContext> => {

const mutationKey = ['postUnifiedFeedback'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUnifiedFeedback>>, {data: PostUnifiedFeedbackBody}> = (props) => {
          const {data} = props ?? {};

          return  postUnifiedFeedback(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostUnifiedFeedbackMutationResult = NonNullable<Awaited<ReturnType<typeof postUnifiedFeedback>>>
    export type PostUnifiedFeedbackMutationBody = PostUnifiedFeedbackBody
    export type PostUnifiedFeedbackMutationError = void | void

    /**
 * @summary Feedback
 */
export const usePostUnifiedFeedback = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUnifiedFeedback>>, TError,{data: PostUnifiedFeedbackBody}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUnifiedFeedback>>,
        TError,
        {data: PostUnifiedFeedbackBody},
        TContext
      > => {

      const mutationOptions = getPostUnifiedFeedbackMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Send Feedback web.
 * @summary FeedbackWeb
 */
export const postFeedbackWeb = (
    postFeedbackWebBody: PostFeedbackWebBody,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`toggl_version`, postFeedbackWebBody.toggl_version)
formUrlEncoded.append(`date`, postFeedbackWebBody.date)
formUrlEncoded.append(`details`, postFeedbackWebBody.details)
if(postFeedbackWebBody.update_channel !== undefined) {
 formUrlEncoded.append(`update_channel`, postFeedbackWebBody.update_channel)
 }
if(postFeedbackWebBody.subject !== undefined) {
 formUrlEncoded.append(`subject`, postFeedbackWebBody.subject)
 }
if(postFeedbackWebBody.latest !== undefined) {
 formUrlEncoded.append(`latest`, postFeedbackWebBody.latest.toString())
 }
if(postFeedbackWebBody.files !== undefined) {
 formUrlEncoded.append(`files`, postFeedbackWebBody.files)
 }

      return togglAxios<void>(
      {url: `/feedback/web`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      options);
    }
  


export const getPostFeedbackWebMutationOptions = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postFeedbackWeb>>, TError,{data: PostFeedbackWebBody}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postFeedbackWeb>>, TError,{data: PostFeedbackWebBody}, TContext> => {

const mutationKey = ['postFeedbackWeb'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postFeedbackWeb>>, {data: PostFeedbackWebBody}> = (props) => {
          const {data} = props ?? {};

          return  postFeedbackWeb(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostFeedbackWebMutationResult = NonNullable<Awaited<ReturnType<typeof postFeedbackWeb>>>
    export type PostFeedbackWebMutationBody = PostFeedbackWebBody
    export type PostFeedbackWebMutationError = void | void

    /**
 * @summary FeedbackWeb
 */
export const usePostFeedbackWeb = <TError = void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postFeedbackWeb>>, TError,{data: PostFeedbackWebBody}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postFeedbackWeb>>,
        TError,
        {data: PostFeedbackWebBody},
        TContext
      > => {

      const mutationOptions = getPostFeedbackWebMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    