// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { togglAxios } from '../mutators/toggl.js';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns ical file with TEs from last 14 days
 * @summary Ical file
 */
export const getIcal = (
    token: string,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<void>(
      {url: `/ical/workspace_user/${token}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetIcalQueryKey = (token?: string,) => {
    return [
    `/ical/workspace_user/${token}`
    ] as const;
    }

    
export const getGetIcalQueryOptions = <TData = Awaited<ReturnType<typeof getIcal>>, TError = void | void>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIcal>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIcalQueryKey(token);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIcal>>> = ({ signal }) => getIcal(token, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIcal>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIcalQueryResult = NonNullable<Awaited<ReturnType<typeof getIcal>>>
export type GetIcalQueryError = void | void


export function useGetIcal<TData = Awaited<ReturnType<typeof getIcal>>, TError = void | void>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIcal>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIcal>>,
          TError,
          Awaited<ReturnType<typeof getIcal>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIcal<TData = Awaited<ReturnType<typeof getIcal>>, TError = void | void>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIcal>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIcal>>,
          TError,
          Awaited<ReturnType<typeof getIcal>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIcal<TData = Awaited<ReturnType<typeof getIcal>>, TError = void | void>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIcal>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Ical file
 */

export function useGetIcal<TData = Awaited<ReturnType<typeof getIcal>>, TError = void | void>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIcal>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIcalQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Reset the iCal token for a given workspace.
 * @summary Reset iCal token
 */
export const postWorkspaceIcalReset = (
    workspaceId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/workspaces/${workspaceId}/ical/reset`, method: 'POST', signal
    },
      options);
    }
  


export const getPostWorkspaceIcalResetMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceIcalReset>>, TError,{workspaceId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceIcalReset>>, TError,{workspaceId: number}, TContext> => {

const mutationKey = ['postWorkspaceIcalReset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkspaceIcalReset>>, {workspaceId: number}> = (props) => {
          const {workspaceId} = props ?? {};

          return  postWorkspaceIcalReset(workspaceId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWorkspaceIcalResetMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkspaceIcalReset>>>
    
    export type PostWorkspaceIcalResetMutationError = string | string | string

    /**
 * @summary Reset iCal token
 */
export const usePostWorkspaceIcalReset = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceIcalReset>>, TError,{workspaceId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkspaceIcalReset>>,
        TError,
        {workspaceId: number},
        TContext
      > => {

      const mutationOptions = getPostWorkspaceIcalResetMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Toggle the iCal token on/off for a given workspace.
 * @summary Toggle the iCal token
 */
export const postWorkspaceIcalToggle = (
    workspaceId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/workspaces/${workspaceId}/ical/toggle`, method: 'POST', signal
    },
      options);
    }
  


export const getPostWorkspaceIcalToggleMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceIcalToggle>>, TError,{workspaceId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceIcalToggle>>, TError,{workspaceId: number}, TContext> => {

const mutationKey = ['postWorkspaceIcalToggle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkspaceIcalToggle>>, {workspaceId: number}> = (props) => {
          const {workspaceId} = props ?? {};

          return  postWorkspaceIcalToggle(workspaceId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWorkspaceIcalToggleMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkspaceIcalToggle>>>
    
    export type PostWorkspaceIcalToggleMutationError = string | string | string

    /**
 * @summary Toggle the iCal token
 */
export const usePostWorkspaceIcalToggle = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceIcalToggle>>, TError,{workspaceId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkspaceIcalToggle>>,
        TError,
        {workspaceId: number},
        TContext
      > => {

      const mutationOptions = getPostWorkspaceIcalToggleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    