// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DtoEmployeeProfitability,
  DtoProjectProfitability,
  ProjectsProjectTrend,
  ProjectsProjectTrends
} from './togglAPI.schemas.js';

import { togglAxios } from '../mutators/toggl.js';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns the projects' data trends projects from a workspace.
 * @summary Load projects' data trends
 */
export const postInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjects = (
    workspaceId: number,
    projectsProjectTrend: ProjectsProjectTrend,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ProjectsProjectTrends[]>(
      {url: `/insights/api/v1/workspace/${workspaceId}/data_trends/projects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: projectsProjectTrend, signal
    },
      options);
    }
  


export const getPostInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjectsMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjects>>, TError,{workspaceId: number;data: ProjectsProjectTrend}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjects>>, TError,{workspaceId: number;data: ProjectsProjectTrend}, TContext> => {

const mutationKey = ['postInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjects'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjects>>, {workspaceId: number;data: ProjectsProjectTrend}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjects(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjectsMutationResult = NonNullable<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjects>>>
    export type PostInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjectsMutationBody = ProjectsProjectTrend
    export type PostInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjectsMutationError = string | string | string | string

    /**
 * @summary Load projects' data trends
 */
export const usePostInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjects = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjects>>, TError,{workspaceId: number;data: ProjectsProjectTrend}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjects>>,
        TError,
        {workspaceId: number;data: ProjectsProjectTrend},
        TContext
      > => {

      const mutationOptions = getPostInsightsApiV1WorkspaceWorkspaceIdDataTrendsProjectsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Downloads employee profitability insights in the specified format: csv or xlsx.
 * @summary Export employee profitability insights
 */
export const postInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtension = (
    workspaceId: string,
    extension: string,
    dtoEmployeeProfitability: DtoEmployeeProfitability,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/insights/api/v1/workspace/${workspaceId}/profitability/employees.${extension}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoEmployeeProfitability, signal
    },
      options);
    }
  


export const getPostInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtensionMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtension>>, TError,{workspaceId: string;extension: string;data: DtoEmployeeProfitability}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtension>>, TError,{workspaceId: string;extension: string;data: DtoEmployeeProfitability}, TContext> => {

const mutationKey = ['postInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtension'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtension>>, {workspaceId: string;extension: string;data: DtoEmployeeProfitability}> = (props) => {
          const {workspaceId,extension,data} = props ?? {};

          return  postInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtension(workspaceId,extension,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtensionMutationResult = NonNullable<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtension>>>
    export type PostInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtensionMutationBody = DtoEmployeeProfitability
    export type PostInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtensionMutationError = string | string | string

    /**
 * @summary Export employee profitability insights
 */
export const usePostInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtension = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtension>>, TError,{workspaceId: string;extension: string;data: DtoEmployeeProfitability}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtension>>,
        TError,
        {workspaceId: string;extension: string;data: DtoEmployeeProfitability},
        TContext
      > => {

      const mutationOptions = getPostInsightsApiV1WorkspaceWorkspaceIdProfitabilityEmployeesExtensionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Downloads profitability project insights in the specified format: csv or xlsx.
 * @summary Export profitability project insights
 */
export const postInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtension = (
    workspaceId: string,
    extension: string,
    dtoProjectProfitability: DtoProjectProfitability,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/insights/api/v1/workspace/${workspaceId}/profitability/projects.${extension}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoProjectProfitability, signal
    },
      options);
    }
  


export const getPostInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtensionMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtension>>, TError,{workspaceId: string;extension: string;data: DtoProjectProfitability}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtension>>, TError,{workspaceId: string;extension: string;data: DtoProjectProfitability}, TContext> => {

const mutationKey = ['postInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtension'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtension>>, {workspaceId: string;extension: string;data: DtoProjectProfitability}> = (props) => {
          const {workspaceId,extension,data} = props ?? {};

          return  postInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtension(workspaceId,extension,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtensionMutationResult = NonNullable<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtension>>>
    export type PostInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtensionMutationBody = DtoProjectProfitability
    export type PostInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtensionMutationError = string | string | string

    /**
 * @summary Export profitability project insights
 */
export const usePostInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtension = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtension>>, TError,{workspaceId: string;extension: string;data: DtoProjectProfitability}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtension>>,
        TError,
        {workspaceId: string;extension: string;data: DtoProjectProfitability},
        TContext
      > => {

      const mutationOptions = getPostInsightsApiV1WorkspaceWorkspaceIdProfitabilityProjectsExtensionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Downloads projects data trends in the specified format: csv or xlsx.
 * @summary Export projects data trends
 */
export const postInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtension = (
    workspaceId: number,
    extension: string,
    projectsProjectTrend: ProjectsProjectTrend,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ProjectsProjectTrends[]>(
      {url: `/insights/api/v1/workspace/${workspaceId}/trends/projects.${extension}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: projectsProjectTrend, signal
    },
      options);
    }
  


export const getPostInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtensionMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtension>>, TError,{workspaceId: number;extension: string;data: ProjectsProjectTrend}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtension>>, TError,{workspaceId: number;extension: string;data: ProjectsProjectTrend}, TContext> => {

const mutationKey = ['postInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtension'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtension>>, {workspaceId: number;extension: string;data: ProjectsProjectTrend}> = (props) => {
          const {workspaceId,extension,data} = props ?? {};

          return  postInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtension(workspaceId,extension,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtensionMutationResult = NonNullable<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtension>>>
    export type PostInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtensionMutationBody = ProjectsProjectTrend
    export type PostInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtensionMutationError = string | string | string

    /**
 * @summary Export projects data trends
 */
export const usePostInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtension = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtension>>, TError,{workspaceId: number;extension: string;data: ProjectsProjectTrend}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtension>>,
        TError,
        {workspaceId: number;extension: string;data: ProjectsProjectTrend},
        TContext
      > => {

      const mutationOptions = getPostInsightsApiV1WorkspaceWorkspaceIdTrendsProjectsExtensionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    