// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InvitationPost,
  InvitationResult,
  ModelsSSOInvitation
} from './togglAPI.schemas';

import { togglAxios } from '../mutators/toggl';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns an invitation data by code.
 * @summary Get an invitation
 */
export const getInvitations = (
    invitationCode: string,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsSSOInvitation>(
      {url: `/invitations/${invitationCode}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetInvitationsQueryKey = (invitationCode?: string,) => {
    return [
    `/invitations/${invitationCode}`
    ] as const;
    }

    
export const getGetInvitationsQueryOptions = <TData = Awaited<ReturnType<typeof getInvitations>>, TError = string | string>(invitationCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitations>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInvitationsQueryKey(invitationCode);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInvitations>>> = ({ signal }) => getInvitations(invitationCode, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(invitationCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInvitations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetInvitationsQueryResult = NonNullable<Awaited<ReturnType<typeof getInvitations>>>
export type GetInvitationsQueryError = string | string


export function useGetInvitations<TData = Awaited<ReturnType<typeof getInvitations>>, TError = string | string>(
 invitationCode: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvitations>>,
          TError,
          Awaited<ReturnType<typeof getInvitations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetInvitations<TData = Awaited<ReturnType<typeof getInvitations>>, TError = string | string>(
 invitationCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getInvitations>>,
          TError,
          Awaited<ReturnType<typeof getInvitations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetInvitations<TData = Awaited<ReturnType<typeof getInvitations>>, TError = string | string>(
 invitationCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitations>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get an invitation
 */

export function useGetInvitations<TData = Awaited<ReturnType<typeof getInvitations>>, TError = string | string>(
 invitationCode: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getInvitations>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetInvitationsQueryOptions(invitationCode,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * User connected with invitation is marked as deleted.
 * @summary Rejects invitation
 */
export const postRejectInvitation = (
    invitationCode: string,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/organizations/invitations/${invitationCode}/reject`, method: 'POST', signal
    },
      options);
    }
  


export const getPostRejectInvitationMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRejectInvitation>>, TError,{invitationCode: string}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postRejectInvitation>>, TError,{invitationCode: string}, TContext> => {

const mutationKey = ['postRejectInvitation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRejectInvitation>>, {invitationCode: string}> = (props) => {
          const {invitationCode} = props ?? {};

          return  postRejectInvitation(invitationCode,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostRejectInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof postRejectInvitation>>>
    
    export type PostRejectInvitationMutationError = string | string

    /**
 * @summary Rejects invitation
 */
export const usePostRejectInvitation = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRejectInvitation>>, TError,{invitationCode: string}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postRejectInvitation>>,
        TError,
        {invitationCode: string},
        TContext
      > => {

      const mutationOptions = getPostRejectInvitationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Creates a new invitation for the user.
 * @summary Creates a new invitation for the user
 */
export const postOrganizationInvitation = (
    organizationId: number,
    invitationPost: InvitationPost,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<InvitationResult>(
      {url: `/organizations/${organizationId}/invitations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: invitationPost, signal
    },
      options);
    }
  


export const getPostOrganizationInvitationMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrganizationInvitation>>, TError,{organizationId: number;data: InvitationPost}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postOrganizationInvitation>>, TError,{organizationId: number;data: InvitationPost}, TContext> => {

const mutationKey = ['postOrganizationInvitation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrganizationInvitation>>, {organizationId: number;data: InvitationPost}> = (props) => {
          const {organizationId,data} = props ?? {};

          return  postOrganizationInvitation(organizationId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostOrganizationInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof postOrganizationInvitation>>>
    export type PostOrganizationInvitationMutationBody = InvitationPost
    export type PostOrganizationInvitationMutationError = string | string

    /**
 * @summary Creates a new invitation for the user
 */
export const usePostOrganizationInvitation = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrganizationInvitation>>, TError,{organizationId: number;data: InvitationPost}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postOrganizationInvitation>>,
        TError,
        {organizationId: number;data: InvitationPost},
        TContext
      > => {

      const mutationOptions = getPostOrganizationInvitationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Resend invitation email to user.
 * @summary Resends user their invitation
 */
export const putInvitation = (
    organizationId: number,
    invitationId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<string>(
      {url: `/organizations/${organizationId}/invitations/${invitationId}/resend`, method: 'PUT'
    },
      options);
    }
  


export const getPutInvitationMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putInvitation>>, TError,{organizationId: number;invitationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof putInvitation>>, TError,{organizationId: number;invitationId: number}, TContext> => {

const mutationKey = ['putInvitation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putInvitation>>, {organizationId: number;invitationId: number}> = (props) => {
          const {organizationId,invitationId} = props ?? {};

          return  putInvitation(organizationId,invitationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof putInvitation>>>
    
    export type PutInvitationMutationError = string | string

    /**
 * @summary Resends user their invitation
 */
export const usePutInvitation = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putInvitation>>, TError,{organizationId: number;invitationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putInvitation>>,
        TError,
        {organizationId: number;invitationId: number},
        TContext
      > => {

      const mutationOptions = getPutInvitationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    