// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ModelsMobileFeedback
} from './togglAPI.schemas';

import { togglAxios } from '../mutators/toggl';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Send Mobile Feedback.
 * @summary MobileFeedback
 */
export const postMobileFeedback = (
    modelsMobileFeedback: ModelsMobileFeedback,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/mobile/feedback`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: modelsMobileFeedback, signal
    },
      options);
    }
  


export const getPostMobileFeedbackMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMobileFeedback>>, TError,{data: ModelsMobileFeedback}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postMobileFeedback>>, TError,{data: ModelsMobileFeedback}, TContext> => {

const mutationKey = ['postMobileFeedback'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMobileFeedback>>, {data: ModelsMobileFeedback}> = (props) => {
          const {data} = props ?? {};

          return  postMobileFeedback(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostMobileFeedbackMutationResult = NonNullable<Awaited<ReturnType<typeof postMobileFeedback>>>
    export type PostMobileFeedbackMutationBody = ModelsMobileFeedback
    export type PostMobileFeedbackMutationError = string | string

    /**
 * @summary MobileFeedback
 */
export const usePostMobileFeedback = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMobileFeedback>>, TError,{data: ModelsMobileFeedback}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postMobileFeedback>>,
        TError,
        {data: ModelsMobileFeedback},
        TContext
      > => {

      const mutationOptions = getPostMobileFeedbackMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    