// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetFeatureUpsellMulti200
} from './togglAPI.schemas';

import { togglAxios } from '../mutators/toggl';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Gets feature upsell information for all organizations the user has access to
 * @summary Get feature upsell for multiple organizations
 */
export const getFeatureUpsellMulti = (
    organizationId: string,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<GetFeatureUpsellMulti200>(
      {url: `/organizations/${organizationId}/subscription/feature_upsell_multi`, method: 'POST', signal
    },
      options);
    }
  


export const getGetFeatureUpsellMultiMutationOptions = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getFeatureUpsellMulti>>, TError,{organizationId: string}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof getFeatureUpsellMulti>>, TError,{organizationId: string}, TContext> => {

const mutationKey = ['getFeatureUpsellMulti'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getFeatureUpsellMulti>>, {organizationId: string}> = (props) => {
          const {organizationId} = props ?? {};

          return  getFeatureUpsellMulti(organizationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetFeatureUpsellMultiMutationResult = NonNullable<Awaited<ReturnType<typeof getFeatureUpsellMulti>>>
    
    export type GetFeatureUpsellMultiMutationError = string

    /**
 * @summary Get feature upsell for multiple organizations
 */
export const useGetFeatureUpsellMulti = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getFeatureUpsellMulti>>, TError,{organizationId: string}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getFeatureUpsellMulti>>,
        TError,
        {organizationId: string},
        TContext
      > => {

      const mutationOptions = getGetFeatureUpsellMultiMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns a Purchase Order document in PDF form.
 * @summary PurchaseOrderPdf
 */
export const getOrganizationPurchaseOrderPdf = (
    organizationId: number,
    purchaseOrderUid: string,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/organizations/${organizationId}/subscription/purchase_orders/${purchaseOrderUid}.pdf`, method: 'GET', signal
    },
      options);
    }
  



export const getGetOrganizationPurchaseOrderPdfQueryKey = (organizationId?: number,
    purchaseOrderUid?: string,) => {
    return [
    `/organizations/${organizationId}/subscription/purchase_orders/${purchaseOrderUid}.pdf`
    ] as const;
    }

    
export const getGetOrganizationPurchaseOrderPdfQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>, TError = string>(organizationId: number,
    purchaseOrderUid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrganizationPurchaseOrderPdfQueryKey(organizationId,purchaseOrderUid);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>> = ({ signal }) => getOrganizationPurchaseOrderPdf(organizationId,purchaseOrderUid, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(organizationId && purchaseOrderUid), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetOrganizationPurchaseOrderPdfQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>>
export type GetOrganizationPurchaseOrderPdfQueryError = string


export function useGetOrganizationPurchaseOrderPdf<TData = Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>, TError = string>(
 organizationId: number,
    purchaseOrderUid: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>,
          TError,
          Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOrganizationPurchaseOrderPdf<TData = Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>, TError = string>(
 organizationId: number,
    purchaseOrderUid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>,
          TError,
          Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetOrganizationPurchaseOrderPdf<TData = Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>, TError = string>(
 organizationId: number,
    purchaseOrderUid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary PurchaseOrderPdf
 */

export function useGetOrganizationPurchaseOrderPdf<TData = Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>, TError = string>(
 organizationId: number,
    purchaseOrderUid: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationPurchaseOrderPdf>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetOrganizationPurchaseOrderPdfQueryOptions(organizationId,purchaseOrderUid,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



