// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import { togglAxios } from '../mutators/toggl.js';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Applies the given promotion code to organization's customer
If the customer already has the promotion code, then it will be overridden
 * @summary Applies the given promotion code to organization's customer
 */
export const postPromotionCode = (
    organizationId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<void>(
      {url: `/organizations/${organizationId}/subscription/promocode`, method: 'POST', signal
    },
      options);
    }
  


export const getPostPromotionCodeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPromotionCode>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postPromotionCode>>, TError,{organizationId: number}, TContext> => {

const mutationKey = ['postPromotionCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPromotionCode>>, {organizationId: number}> = (props) => {
          const {organizationId} = props ?? {};

          return  postPromotionCode(organizationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPromotionCodeMutationResult = NonNullable<Awaited<ReturnType<typeof postPromotionCode>>>
    
    export type PostPromotionCodeMutationError = void

    /**
 * @summary Applies the given promotion code to organization's customer
 */
export const usePostPromotionCode = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPromotionCode>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postPromotionCode>>,
        TError,
        {organizationId: number},
        TContext
      > => {

      const mutationOptions = getPostPromotionCodeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Removes any discount (promotion code) applied to the organization's customer
 * @summary Removes any discount (promotion code) applied to the organization's customer
 */
export const deletePromotionCode = (
    organizationId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<void>(
      {url: `/organizations/${organizationId}/subscription/promocode`, method: 'DELETE'
    },
      options);
    }
  


export const getDeletePromotionCodeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePromotionCode>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePromotionCode>>, TError,{organizationId: number}, TContext> => {

const mutationKey = ['deletePromotionCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePromotionCode>>, {organizationId: number}> = (props) => {
          const {organizationId} = props ?? {};

          return  deletePromotionCode(organizationId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeletePromotionCodeMutationResult = NonNullable<Awaited<ReturnType<typeof deletePromotionCode>>>
    
    export type DeletePromotionCodeMutationError = void

    /**
 * @summary Removes any discount (promotion code) applied to the organization's customer
 */
export const useDeletePromotionCode = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePromotionCode>>, TError,{organizationId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePromotionCode>>,
        TError,
        {organizationId: number},
        TContext
      > => {

      const mutationOptions = getDeletePromotionCodeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    