// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteWorkspaceProjectParams,
  GetProjectsBody,
  GetProjectsParams,
  GetWorkspaceProjectPeriodsParams,
  GetWorkspaceProjectUsersParams,
  ModelsProject,
  ModelsProjectStatistics,
  ModelsProjectUser,
  ModelsProjectUserWithMeta,
  ModelsRecurringPeriod,
  PatchWorkspaceProjectUsersIdsParams,
  PostWorkspaceProjectUsersPaginatedParams,
  ProjectPayloadBody,
  ProjectsPatchOutput,
  ProjectsPatchPost,
  ProjectsPayload,
  ProjectsPinnedProjectPayload,
  ProjectsTaskCountPayload,
  UserOutput,
  UserPostPayload,
  UserPutPayload,
  WorkspaceProjectsTaskCount200Item
} from './togglAPI.schemas.js';

import { togglAxios } from '../mutators/toggl.js';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List all projects users for a given workspace.
 * @summary Get workspace projects users
 */
export const getWorkspaceProjectUsers = (
    workspaceId: number,
    params?: GetWorkspaceProjectUsersParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsProjectUser[]>(
      {url: `/workspaces/${workspaceId}/project_users`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetWorkspaceProjectUsersQueryKey = (workspaceId?: number,
    params?: GetWorkspaceProjectUsersParams,) => {
    return [
    `/workspaces/${workspaceId}/project_users`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetWorkspaceProjectUsersQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspaceProjectUsers>>, TError = string | string | string>(workspaceId: number,
    params?: GetWorkspaceProjectUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectUsers>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspaceProjectUsersQueryKey(workspaceId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspaceProjectUsers>>> = ({ signal }) => getWorkspaceProjectUsers(workspaceId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWorkspaceProjectUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceProjectUsers>>>
export type GetWorkspaceProjectUsersQueryError = string | string | string


export function useGetWorkspaceProjectUsers<TData = Awaited<ReturnType<typeof getWorkspaceProjectUsers>>, TError = string | string | string>(
 workspaceId: number,
    params: undefined |  GetWorkspaceProjectUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceProjectUsers>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceProjectUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceProjectUsers<TData = Awaited<ReturnType<typeof getWorkspaceProjectUsers>>, TError = string | string | string>(
 workspaceId: number,
    params?: GetWorkspaceProjectUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceProjectUsers>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceProjectUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceProjectUsers<TData = Awaited<ReturnType<typeof getWorkspaceProjectUsers>>, TError = string | string | string>(
 workspaceId: number,
    params?: GetWorkspaceProjectUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectUsers>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get workspace projects users
 */

export function useGetWorkspaceProjectUsers<TData = Awaited<ReturnType<typeof getWorkspaceProjectUsers>>, TError = string | string | string>(
 workspaceId: number,
    params?: GetWorkspaceProjectUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectUsers>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWorkspaceProjectUsersQueryOptions(workspaceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Include a project user for a given workspace.
 * @summary Add an user into workspace projects users
 */
export const postWorkspaceProjectUsers = (
    workspaceId: number,
    userPostPayload: UserPostPayload,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsProjectUser>(
      {url: `/workspaces/${workspaceId}/project_users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: userPostPayload, signal
    },
      options);
    }
  


export const getPostWorkspaceProjectUsersMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceProjectUsers>>, TError,{workspaceId: number;data: UserPostPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceProjectUsers>>, TError,{workspaceId: number;data: UserPostPayload}, TContext> => {

const mutationKey = ['postWorkspaceProjectUsers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkspaceProjectUsers>>, {workspaceId: number;data: UserPostPayload}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postWorkspaceProjectUsers(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWorkspaceProjectUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkspaceProjectUsers>>>
    export type PostWorkspaceProjectUsersMutationBody = UserPostPayload
    export type PostWorkspaceProjectUsersMutationError = string | string | string

    /**
 * @summary Add an user into workspace projects users
 */
export const usePostWorkspaceProjectUsers = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceProjectUsers>>, TError,{workspaceId: number;data: UserPostPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkspaceProjectUsers>>,
        TError,
        {workspaceId: number;data: UserPostPayload},
        TContext
      > => {

      const mutationOptions = getPostWorkspaceProjectUsersMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List projects users for a given workspace and set of project IDs paginated.
 * @summary Get workspace projects users paginated
 */
export const postWorkspaceProjectUsersPaginated = (
    workspaceId: number,
    postWorkspaceProjectUsersPaginatedBody: number[],
    params?: PostWorkspaceProjectUsersPaginatedParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsProjectUserWithMeta[]>(
      {url: `/workspaces/${workspaceId}/project_users/paginated`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postWorkspaceProjectUsersPaginatedBody,
        params, signal
    },
      options);
    }
  


export const getPostWorkspaceProjectUsersPaginatedMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceProjectUsersPaginated>>, TError,{workspaceId: number;data: number[];params?: PostWorkspaceProjectUsersPaginatedParams}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceProjectUsersPaginated>>, TError,{workspaceId: number;data: number[];params?: PostWorkspaceProjectUsersPaginatedParams}, TContext> => {

const mutationKey = ['postWorkspaceProjectUsersPaginated'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkspaceProjectUsersPaginated>>, {workspaceId: number;data: number[];params?: PostWorkspaceProjectUsersPaginatedParams}> = (props) => {
          const {workspaceId,data,params} = props ?? {};

          return  postWorkspaceProjectUsersPaginated(workspaceId,data,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWorkspaceProjectUsersPaginatedMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkspaceProjectUsersPaginated>>>
    export type PostWorkspaceProjectUsersPaginatedMutationBody = number[]
    export type PostWorkspaceProjectUsersPaginatedMutationError = void

    /**
 * @summary Get workspace projects users paginated
 */
export const usePostWorkspaceProjectUsersPaginated = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceProjectUsersPaginated>>, TError,{workspaceId: number;data: number[];params?: PostWorkspaceProjectUsersPaginatedParams}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkspaceProjectUsersPaginated>>,
        TError,
        {workspaceId: number;data: number[];params?: PostWorkspaceProjectUsersPaginatedParams},
        TContext
      > => {

      const mutationOptions = getPostWorkspaceProjectUsersPaginatedMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Patch a list of project users for a given workspace.
 * @summary Patch project users from workspace
 */
export const patchWorkspaceProjectUsersIds = (
    workspaceId: number,
    projectUserIds: string,
    params: PatchWorkspaceProjectUsersIdsParams,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<UserOutput>(
      {url: `/workspaces/${workspaceId}/project_users/${projectUserIds}`, method: 'PATCH',
        params
    },
      options);
    }
  


export const getPatchWorkspaceProjectUsersIdsMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchWorkspaceProjectUsersIds>>, TError,{workspaceId: number;projectUserIds: string;params: PatchWorkspaceProjectUsersIdsParams}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchWorkspaceProjectUsersIds>>, TError,{workspaceId: number;projectUserIds: string;params: PatchWorkspaceProjectUsersIdsParams}, TContext> => {

const mutationKey = ['patchWorkspaceProjectUsersIds'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchWorkspaceProjectUsersIds>>, {workspaceId: number;projectUserIds: string;params: PatchWorkspaceProjectUsersIdsParams}> = (props) => {
          const {workspaceId,projectUserIds,params} = props ?? {};

          return  patchWorkspaceProjectUsersIds(workspaceId,projectUserIds,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchWorkspaceProjectUsersIdsMutationResult = NonNullable<Awaited<ReturnType<typeof patchWorkspaceProjectUsersIds>>>
    
    export type PatchWorkspaceProjectUsersIdsMutationError = string | string | string

    /**
 * @summary Patch project users from workspace
 */
export const usePatchWorkspaceProjectUsersIds = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchWorkspaceProjectUsersIds>>, TError,{workspaceId: number;projectUserIds: string;params: PatchWorkspaceProjectUsersIdsParams}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchWorkspaceProjectUsersIds>>,
        TError,
        {workspaceId: number;projectUserIds: string;params: PatchWorkspaceProjectUsersIdsParams},
        TContext
      > => {

      const mutationOptions = getPatchWorkspaceProjectUsersIdsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Update the data for a project user for a given workspace.
 * @summary Update an user into workspace projects users
 */
export const putWorkspaceProjectUsers = (
    workspaceId: number,
    projectUserId: number,
    userPutPayload: UserPutPayload,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<ModelsProjectUser>(
      {url: `/workspaces/${workspaceId}/project_users/${projectUserId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: userPutPayload
    },
      options);
    }
  


export const getPutWorkspaceProjectUsersMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceProjectUsers>>, TError,{workspaceId: number;projectUserId: number;data: UserPutPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceProjectUsers>>, TError,{workspaceId: number;projectUserId: number;data: UserPutPayload}, TContext> => {

const mutationKey = ['putWorkspaceProjectUsers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putWorkspaceProjectUsers>>, {workspaceId: number;projectUserId: number;data: UserPutPayload}> = (props) => {
          const {workspaceId,projectUserId,data} = props ?? {};

          return  putWorkspaceProjectUsers(workspaceId,projectUserId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutWorkspaceProjectUsersMutationResult = NonNullable<Awaited<ReturnType<typeof putWorkspaceProjectUsers>>>
    export type PutWorkspaceProjectUsersMutationBody = UserPutPayload
    export type PutWorkspaceProjectUsersMutationError = string | string | string

    /**
 * @summary Update an user into workspace projects users
 */
export const usePutWorkspaceProjectUsers = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceProjectUsers>>, TError,{workspaceId: number;projectUserId: number;data: UserPutPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putWorkspaceProjectUsers>>,
        TError,
        {workspaceId: number;projectUserId: number;data: UserPutPayload},
        TContext
      > => {

      const mutationOptions = getPutWorkspaceProjectUsersMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a project user for a given workspace.
 * @summary Delete a project user from workspace projects users
 */
export const deleteWorkspaceProjectUsers = (
    workspaceId: number,
    projectUserId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<number>(
      {url: `/workspaces/${workspaceId}/project_users/${projectUserId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteWorkspaceProjectUsersMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceProjectUsers>>, TError,{workspaceId: number;projectUserId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceProjectUsers>>, TError,{workspaceId: number;projectUserId: number}, TContext> => {

const mutationKey = ['deleteWorkspaceProjectUsers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkspaceProjectUsers>>, {workspaceId: number;projectUserId: number}> = (props) => {
          const {workspaceId,projectUserId} = props ?? {};

          return  deleteWorkspaceProjectUsers(workspaceId,projectUserId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkspaceProjectUsersMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspaceProjectUsers>>>
    
    export type DeleteWorkspaceProjectUsersMutationError = string | string | string

    /**
 * @summary Delete a project user from workspace projects users
 */
export const useDeleteWorkspaceProjectUsers = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceProjectUsers>>, TError,{workspaceId: number;projectUserId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWorkspaceProjectUsers>>,
        TError,
        {workspaceId: number;projectUserId: number},
        TContext
      > => {

      const mutationOptions = getDeleteWorkspaceProjectUsersMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get projects for given workspace.
 * @summary WorkspaceProjects
 */
export const getProjects = (
    workspaceId: number,
    getProjectsBody: GetProjectsBody,
    params: GetProjectsParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      const formUrlEncoded = new URLSearchParams();
if(getProjectsBody.active !== undefined) {
 formUrlEncoded.append(`active`, getProjectsBody.active.toString())
 }
if(getProjectsBody.since !== undefined) {
 formUrlEncoded.append(`since`, getProjectsBody.since.toString())
 }
if(getProjectsBody.billable !== undefined) {
 formUrlEncoded.append(`billable`, getProjectsBody.billable.toString())
 }
if(getProjectsBody.user_ids !== undefined) {
 getProjectsBody.user_ids.forEach(value => formUrlEncoded.append(`user_ids`, value));
 }
if(getProjectsBody.client_ids !== undefined) {
 getProjectsBody.client_ids.forEach(value => formUrlEncoded.append(`client_ids`, value));
 }
if(getProjectsBody.group_ids !== undefined) {
 getProjectsBody.group_ids.forEach(value => formUrlEncoded.append(`group_ids`, value));
 }
if(getProjectsBody.project_ids !== undefined) {
 getProjectsBody.project_ids.forEach(value => formUrlEncoded.append(`project_ids`, value));
 }
if(getProjectsBody.statuses !== undefined) {
 getProjectsBody.statuses.forEach(value => formUrlEncoded.append(`statuses`, value));
 }
formUrlEncoded.append(`name`, getProjectsBody.name)
formUrlEncoded.append(`page`, getProjectsBody.page.toString())
formUrlEncoded.append(`sort_field`, getProjectsBody.sort_field)
formUrlEncoded.append(`sort_order`, getProjectsBody.sort_order)
formUrlEncoded.append(`only_templates`, getProjectsBody.only_templates.toString())
if(getProjectsBody.only_me !== undefined) {
 formUrlEncoded.append(`only_me`, getProjectsBody.only_me.toString())
 }
if(getProjectsBody.per_page !== undefined) {
 formUrlEncoded.append(`per_page`, getProjectsBody.per_page.toString())
 }

      return togglAxios<ModelsProject[]>(
      {url: `/workspaces/${workspaceId}/projects`, method: 'GET',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
        params, signal
    },
      options);
    }
  



export const getGetProjectsQueryKey = (workspaceId?: number,
    getProjectsBody?: GetProjectsBody,
    params?: GetProjectsParams,) => {
    return [
    `/workspaces/${workspaceId}/projects`, ...(params ? [params]: []), getProjectsBody
    ] as const;
    }

    
export const getGetProjectsQueryOptions = <TData = Awaited<ReturnType<typeof getProjects>>, TError = string | string>(workspaceId: number,
    getProjectsBody: GetProjectsBody,
    params: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectsQueryKey(workspaceId,getProjectsBody,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjects>>> = ({ signal }) => getProjects(workspaceId,getProjectsBody,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getProjects>>>
export type GetProjectsQueryError = string | string


export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = string | string>(
 workspaceId: number,
    getProjectsBody: GetProjectsBody,
    params: GetProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = string | string>(
 workspaceId: number,
    getProjectsBody: GetProjectsBody,
    params: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = string | string>(
 workspaceId: number,
    getProjectsBody: GetProjectsBody,
    params: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary WorkspaceProjects
 */

export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = string | string>(
 workspaceId: number,
    getProjectsBody: GetProjectsBody,
    params: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetProjectsQueryOptions(workspaceId,getProjectsBody,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create project for given workspace.
 * @summary WorkspaceProjects
 */
export const postWorkspaceProjectCreate = (
    workspaceId: number,
    projectPayloadBody: ProjectPayloadBody,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsProject>(
      {url: `/workspaces/${workspaceId}/projects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: projectPayloadBody, signal
    },
      options);
    }
  


export const getPostWorkspaceProjectCreateMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceProjectCreate>>, TError,{workspaceId: number;data: ProjectPayloadBody}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceProjectCreate>>, TError,{workspaceId: number;data: ProjectPayloadBody}, TContext> => {

const mutationKey = ['postWorkspaceProjectCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkspaceProjectCreate>>, {workspaceId: number;data: ProjectPayloadBody}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postWorkspaceProjectCreate(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWorkspaceProjectCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkspaceProjectCreate>>>
    export type PostWorkspaceProjectCreateMutationBody = ProjectPayloadBody
    export type PostWorkspaceProjectCreateMutationError = string | string

    /**
 * @summary WorkspaceProjects
 */
export const usePostWorkspaceProjectCreate = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceProjectCreate>>, TError,{workspaceId: number;data: ProjectPayloadBody}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkspaceProjectCreate>>,
        TError,
        {workspaceId: number;data: ProjectPayloadBody},
        TContext
      > => {

      const mutationOptions = getPostWorkspaceProjectCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get projects billable amounts
 * @summary Projects
 */
export const postWorkspacesWorkspaceIdProjectsBillableAmounts = (
    workspaceId: number,
    projectsPayload: ProjectsPayload,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsProject[]>(
      {url: `/workspaces/${workspaceId}/projects/billable-amounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: projectsPayload, signal
    },
      options);
    }
  


export const getPostWorkspacesWorkspaceIdProjectsBillableAmountsMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdProjectsBillableAmounts>>, TError,{workspaceId: number;data: ProjectsPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdProjectsBillableAmounts>>, TError,{workspaceId: number;data: ProjectsPayload}, TContext> => {

const mutationKey = ['postWorkspacesWorkspaceIdProjectsBillableAmounts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdProjectsBillableAmounts>>, {workspaceId: number;data: ProjectsPayload}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postWorkspacesWorkspaceIdProjectsBillableAmounts(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWorkspacesWorkspaceIdProjectsBillableAmountsMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdProjectsBillableAmounts>>>
    export type PostWorkspacesWorkspaceIdProjectsBillableAmountsMutationBody = ProjectsPayload
    export type PostWorkspacesWorkspaceIdProjectsBillableAmountsMutationError = string | string | string

    /**
 * @summary Projects
 */
export const usePostWorkspacesWorkspaceIdProjectsBillableAmounts = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspacesWorkspaceIdProjectsBillableAmounts>>, TError,{workspaceId: number;data: ProjectsPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkspacesWorkspaceIdProjectsBillableAmounts>>,
        TError,
        {workspaceId: number;data: ProjectsPayload},
        TContext
      > => {

      const mutationOptions = getPostWorkspacesWorkspaceIdProjectsBillableAmountsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Retrieves the task count for the specified projects
 * @summary WorkspaceProjectsTaskCount
 */
export const workspaceProjectsTaskCount = (
    workspaceId: number,
    projectsTaskCountPayload: ProjectsTaskCountPayload,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<WorkspaceProjectsTaskCount200Item[]>(
      {url: `/workspaces/${workspaceId}/projects/task_count`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: projectsTaskCountPayload, signal
    },
      options);
    }
  


export const getWorkspaceProjectsTaskCountMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceProjectsTaskCount>>, TError,{workspaceId: number;data: ProjectsTaskCountPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof workspaceProjectsTaskCount>>, TError,{workspaceId: number;data: ProjectsTaskCountPayload}, TContext> => {

const mutationKey = ['workspaceProjectsTaskCount'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspaceProjectsTaskCount>>, {workspaceId: number;data: ProjectsTaskCountPayload}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  workspaceProjectsTaskCount(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type WorkspaceProjectsTaskCountMutationResult = NonNullable<Awaited<ReturnType<typeof workspaceProjectsTaskCount>>>
    export type WorkspaceProjectsTaskCountMutationBody = ProjectsTaskCountPayload
    export type WorkspaceProjectsTaskCountMutationError = string | string

    /**
 * @summary WorkspaceProjectsTaskCount
 */
export const useWorkspaceProjectsTaskCount = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceProjectsTaskCount>>, TError,{workspaceId: number;data: ProjectsTaskCountPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspaceProjectsTaskCount>>,
        TError,
        {workspaceId: number;data: ProjectsTaskCountPayload},
        TContext
      > => {

      const mutationOptions = getWorkspaceProjectsTaskCountMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get projects templates for given workspace.
 * @summary WorkspaceProjectsTemplates
 */
export const getProjectsTemplates = (
    workspaceId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/workspaces/${workspaceId}/projects/templates`, method: 'GET', signal
    },
      options);
    }
  



export const getGetProjectsTemplatesQueryKey = (workspaceId?: number,) => {
    return [
    `/workspaces/${workspaceId}/projects/templates`
    ] as const;
    }

    
export const getGetProjectsTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof getProjectsTemplates>>, TError = string | string>(workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsTemplates>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectsTemplatesQueryKey(workspaceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectsTemplates>>> = ({ signal }) => getProjectsTemplates(workspaceId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectsTemplates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetProjectsTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectsTemplates>>>
export type GetProjectsTemplatesQueryError = string | string


export function useGetProjectsTemplates<TData = Awaited<ReturnType<typeof getProjectsTemplates>>, TError = string | string>(
 workspaceId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsTemplates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectsTemplates>>,
          TError,
          Awaited<ReturnType<typeof getProjectsTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetProjectsTemplates<TData = Awaited<ReturnType<typeof getProjectsTemplates>>, TError = string | string>(
 workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsTemplates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectsTemplates>>,
          TError,
          Awaited<ReturnType<typeof getProjectsTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetProjectsTemplates<TData = Awaited<ReturnType<typeof getProjectsTemplates>>, TError = string | string>(
 workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsTemplates>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary WorkspaceProjectsTemplates
 */

export function useGetProjectsTemplates<TData = Awaited<ReturnType<typeof getProjectsTemplates>>, TError = string | string>(
 workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsTemplates>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetProjectsTemplatesQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Bulk editing workspace projects.
 * @summary WorkspaceProjects
 */
export const patchWorkspaceProjects = (
    workspaceId: number,
    projectIds: string,
    projectsPatchPost: ProjectsPatchPost,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<ProjectsPatchOutput>(
      {url: `/workspaces/${workspaceId}/projects/${projectIds}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: projectsPatchPost
    },
      options);
    }
  


export const getPatchWorkspaceProjectsMutationOptions = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchWorkspaceProjects>>, TError,{workspaceId: number;projectIds: string;data: ProjectsPatchPost}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchWorkspaceProjects>>, TError,{workspaceId: number;projectIds: string;data: ProjectsPatchPost}, TContext> => {

const mutationKey = ['patchWorkspaceProjects'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchWorkspaceProjects>>, {workspaceId: number;projectIds: string;data: ProjectsPatchPost}> = (props) => {
          const {workspaceId,projectIds,data} = props ?? {};

          return  patchWorkspaceProjects(workspaceId,projectIds,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchWorkspaceProjectsMutationResult = NonNullable<Awaited<ReturnType<typeof patchWorkspaceProjects>>>
    export type PatchWorkspaceProjectsMutationBody = ProjectsPatchPost
    export type PatchWorkspaceProjectsMutationError = string

    /**
 * @summary WorkspaceProjects
 */
export const usePatchWorkspaceProjects = <TError = string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchWorkspaceProjects>>, TError,{workspaceId: number;projectIds: string;data: ProjectsPatchPost}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchWorkspaceProjects>>,
        TError,
        {workspaceId: number;projectIds: string;data: ProjectsPatchPost},
        TContext
      > => {

      const mutationOptions = getPatchWorkspaceProjectsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get project for given workspace.
 * @summary WorkspaceProject
 */
export const getWorkspacesWorkspaceIdProjectsProjectId = (
    workspaceId: number,
    projectId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsProject>(
      {url: `/workspaces/${workspaceId}/projects/${projectId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetWorkspacesWorkspaceIdProjectsProjectIdQueryKey = (workspaceId?: number,
    projectId?: number,) => {
    return [
    `/workspaces/${workspaceId}/projects/${projectId}`
    ] as const;
    }

    
export const getGetWorkspacesWorkspaceIdProjectsProjectIdQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>, TError = string | string | string>(workspaceId: number,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspacesWorkspaceIdProjectsProjectIdQueryKey(workspaceId,projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>> = ({ signal }) => getWorkspacesWorkspaceIdProjectsProjectId(workspaceId,projectId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId && projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWorkspacesWorkspaceIdProjectsProjectIdQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>>
export type GetWorkspacesWorkspaceIdProjectsProjectIdQueryError = string | string | string


export function useGetWorkspacesWorkspaceIdProjectsProjectId<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>,
          TError,
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspacesWorkspaceIdProjectsProjectId<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>,
          TError,
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspacesWorkspaceIdProjectsProjectId<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary WorkspaceProject
 */

export function useGetWorkspacesWorkspaceIdProjectsProjectId<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectId>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWorkspacesWorkspaceIdProjectsProjectIdQueryOptions(workspaceId,projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Update project for given workspace.
 * @summary WorkspaceProject
 */
export const putWorkspaceProject = (
    workspaceId: number,
    projectId: number,
    projectPayloadBody: ProjectPayloadBody,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<ModelsProject>(
      {url: `/workspaces/${workspaceId}/projects/${projectId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: projectPayloadBody
    },
      options);
    }
  


export const getPutWorkspaceProjectMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceProject>>, TError,{workspaceId: number;projectId: number;data: ProjectPayloadBody}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceProject>>, TError,{workspaceId: number;projectId: number;data: ProjectPayloadBody}, TContext> => {

const mutationKey = ['putWorkspaceProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putWorkspaceProject>>, {workspaceId: number;projectId: number;data: ProjectPayloadBody}> = (props) => {
          const {workspaceId,projectId,data} = props ?? {};

          return  putWorkspaceProject(workspaceId,projectId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutWorkspaceProjectMutationResult = NonNullable<Awaited<ReturnType<typeof putWorkspaceProject>>>
    export type PutWorkspaceProjectMutationBody = ProjectPayloadBody
    export type PutWorkspaceProjectMutationError = string | string | string

    /**
 * @summary WorkspaceProject
 */
export const usePutWorkspaceProject = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceProject>>, TError,{workspaceId: number;projectId: number;data: ProjectPayloadBody}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putWorkspaceProject>>,
        TError,
        {workspaceId: number;projectId: number;data: ProjectPayloadBody},
        TContext
      > => {

      const mutationOptions = getPutWorkspaceProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete project for given workspace.
 * @summary WorkspaceProject
 */
export const deleteWorkspaceProject = (
    workspaceId: number,
    projectId: number,
    params?: DeleteWorkspaceProjectParams,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<number>(
      {url: `/workspaces/${workspaceId}/projects/${projectId}`, method: 'DELETE',
        params
    },
      options);
    }
  


export const getDeleteWorkspaceProjectMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceProject>>, TError,{workspaceId: number;projectId: number;params?: DeleteWorkspaceProjectParams}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceProject>>, TError,{workspaceId: number;projectId: number;params?: DeleteWorkspaceProjectParams}, TContext> => {

const mutationKey = ['deleteWorkspaceProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkspaceProject>>, {workspaceId: number;projectId: number;params?: DeleteWorkspaceProjectParams}> = (props) => {
          const {workspaceId,projectId,params} = props ?? {};

          return  deleteWorkspaceProject(workspaceId,projectId,params,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkspaceProjectMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspaceProject>>>
    
    export type DeleteWorkspaceProjectMutationError = string | string | string

    /**
 * @summary WorkspaceProject
 */
export const useDeleteWorkspaceProject = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceProject>>, TError,{workspaceId: number;projectId: number;params?: DeleteWorkspaceProjectParams}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWorkspaceProject>>,
        TError,
        {workspaceId: number;projectId: number;params?: DeleteWorkspaceProjectParams},
        TContext
      > => {

      const mutationOptions = getDeleteWorkspaceProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get recurring project periods for given workspace.
 * @summary Get Recurring Project Periods
 */
export const getWorkspaceProjectPeriods = (
    workspaceId: number,
    projectId: number,
    params?: GetWorkspaceProjectPeriodsParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsRecurringPeriod>(
      {url: `/workspaces/${workspaceId}/projects/${projectId}/periods`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetWorkspaceProjectPeriodsQueryKey = (workspaceId?: number,
    projectId?: number,
    params?: GetWorkspaceProjectPeriodsParams,) => {
    return [
    `/workspaces/${workspaceId}/projects/${projectId}/periods`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetWorkspaceProjectPeriodsQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>, TError = string | string | string>(workspaceId: number,
    projectId: number,
    params?: GetWorkspaceProjectPeriodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspaceProjectPeriodsQueryKey(workspaceId,projectId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>> = ({ signal }) => getWorkspaceProjectPeriods(workspaceId,projectId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId && projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWorkspaceProjectPeriodsQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>>
export type GetWorkspaceProjectPeriodsQueryError = string | string | string


export function useGetWorkspaceProjectPeriods<TData = Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number,
    params: undefined |  GetWorkspaceProjectPeriodsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceProjectPeriods<TData = Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number,
    params?: GetWorkspaceProjectPeriodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceProjectPeriods<TData = Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number,
    params?: GetWorkspaceProjectPeriodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get Recurring Project Periods
 */

export function useGetWorkspaceProjectPeriods<TData = Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number,
    params?: GetWorkspaceProjectPeriodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceProjectPeriods>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWorkspaceProjectPeriodsQueryOptions(workspaceId,projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Pin or unpin a project to top of user's project list
 * @summary WorkspaceProjects
 */
export const postPinnedProject = (
    workspaceId: number,
    projectId: number,
    projectsPinnedProjectPayload: ProjectsPinnedProjectPayload,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<void>(
      {url: `/workspaces/${workspaceId}/projects/${projectId}/pin`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: projectsPinnedProjectPayload, signal
    },
      options);
    }
  


export const getPostPinnedProjectMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPinnedProject>>, TError,{workspaceId: number;projectId: number;data: ProjectsPinnedProjectPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postPinnedProject>>, TError,{workspaceId: number;projectId: number;data: ProjectsPinnedProjectPayload}, TContext> => {

const mutationKey = ['postPinnedProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPinnedProject>>, {workspaceId: number;projectId: number;data: ProjectsPinnedProjectPayload}> = (props) => {
          const {workspaceId,projectId,data} = props ?? {};

          return  postPinnedProject(workspaceId,projectId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPinnedProjectMutationResult = NonNullable<Awaited<ReturnType<typeof postPinnedProject>>>
    export type PostPinnedProjectMutationBody = ProjectsPinnedProjectPayload
    export type PostPinnedProjectMutationError = string | string | string

    /**
 * @summary WorkspaceProjects
 */
export const usePostPinnedProject = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPinnedProject>>, TError,{workspaceId: number;projectId: number;data: ProjectsPinnedProjectPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postPinnedProject>>,
        TError,
        {workspaceId: number;projectId: number;data: ProjectsPinnedProjectPayload},
        TContext
      > => {

      const mutationOptions = getPostPinnedProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get statistics for given workspace and project. For time entry related information, this endpoint does not consider running ones.
 * @summary WorkspaceProject
 */
export const getWorkspacesWorkspaceIdProjectsProjectIdStatistics = (
    workspaceId: number,
    projectId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsProjectStatistics>(
      {url: `/workspaces/${workspaceId}/projects/${projectId}/statistics`, method: 'GET', signal
    },
      options);
    }
  



export const getGetWorkspacesWorkspaceIdProjectsProjectIdStatisticsQueryKey = (workspaceId?: number,
    projectId?: number,) => {
    return [
    `/workspaces/${workspaceId}/projects/${projectId}/statistics`
    ] as const;
    }

    
export const getGetWorkspacesWorkspaceIdProjectsProjectIdStatisticsQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>, TError = string | string | string>(workspaceId: number,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspacesWorkspaceIdProjectsProjectIdStatisticsQueryKey(workspaceId,projectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>> = ({ signal }) => getWorkspacesWorkspaceIdProjectsProjectIdStatistics(workspaceId,projectId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId && projectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWorkspacesWorkspaceIdProjectsProjectIdStatisticsQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>>
export type GetWorkspacesWorkspaceIdProjectsProjectIdStatisticsQueryError = string | string | string


export function useGetWorkspacesWorkspaceIdProjectsProjectIdStatistics<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspacesWorkspaceIdProjectsProjectIdStatistics<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>,
          TError,
          Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspacesWorkspaceIdProjectsProjectIdStatistics<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary WorkspaceProject
 */

export function useGetWorkspacesWorkspaceIdProjectsProjectIdStatistics<TData = Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>, TError = string | string | string>(
 workspaceId: number,
    projectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspacesWorkspaceIdProjectsProjectIdStatistics>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWorkspacesWorkspaceIdProjectsProjectIdStatisticsQueryOptions(workspaceId,projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



