// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers201,
  PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers400,
  PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers500,
  SessionCheckWorkspaceUsersPayload
} from './togglAPI.schemas';

import { togglAxios } from '../mutators/toggl';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Check if the given list of users are members of the given workspace within the organization.
 * @summary Check if the given users are members of the organization.
 */
export const postSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers = (
    productId: number,
    organizationId: number,
    workspaceId: number,
    sessionCheckWorkspaceUsersPayload: SessionCheckWorkspaceUsersPayload,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers201>(
      {url: `/session/${productId}/organizations/${organizationId}/workspaces/${workspaceId}/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sessionCheckWorkspaceUsersPayload, signal
    },
      options);
    }
  


export const getPostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsersMutationOptions = <TError = PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers400 | PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers>>, TError,{productId: number;organizationId: number;workspaceId: number;data: SessionCheckWorkspaceUsersPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers>>, TError,{productId: number;organizationId: number;workspaceId: number;data: SessionCheckWorkspaceUsersPayload}, TContext> => {

const mutationKey = ['postSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers>>, {productId: number;organizationId: number;workspaceId: number;data: SessionCheckWorkspaceUsersPayload}> = (props) => {
          const {productId,organizationId,workspaceId,data} = props ?? {};

          return  postSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers(productId,organizationId,workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers>>>
    export type PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsersMutationBody = SessionCheckWorkspaceUsersPayload
    export type PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsersMutationError = PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers400 | PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers500

    /**
 * @summary Check if the given users are members of the organization.
 */
export const usePostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers = <TError = PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers400 | PostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers>>, TError,{productId: number;organizationId: number;workspaceId: number;data: SessionCheckWorkspaceUsersPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsers>>,
        TError,
        {productId: number;organizationId: number;workspaceId: number;data: SessionCheckWorkspaceUsersPayload},
        TContext
      > => {

      const mutationOptions = getPostSessionProductIdOrganizationsOrganizationIdWorkspacesWorkspaceIdUsersMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    