// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BaseRangePost,
  DtoProjectUsersRequest,
  SummaryExportPDFPost,
  SummaryExportPost,
  SummaryReportPost,
  TotalsReportData,
  UsersProjectUsersSummaryRow
} from './togglAPI.schemas.js';

import { togglAxios } from '../mutators/toggl.js';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns summary user projects.
 * @summary List project users
 */
export const postReportsApiV3WorkspaceWorkspaceIdProjectsSummary = (
    workspaceId: number,
    dtoProjectUsersRequest: DtoProjectUsersRequest,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<UsersProjectUsersSummaryRow[]>(
      {url: `/reports/api/v3/workspace/${workspaceId}/projects/summary`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoProjectUsersRequest, signal
    },
      options);
    }
  


export const getPostReportsApiV3WorkspaceWorkspaceIdProjectsSummaryMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsSummary>>, TError,{workspaceId: number;data: DtoProjectUsersRequest}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsSummary>>, TError,{workspaceId: number;data: DtoProjectUsersRequest}, TContext> => {

const mutationKey = ['postReportsApiV3WorkspaceWorkspaceIdProjectsSummary'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsSummary>>, {workspaceId: number;data: DtoProjectUsersRequest}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postReportsApiV3WorkspaceWorkspaceIdProjectsSummary(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostReportsApiV3WorkspaceWorkspaceIdProjectsSummaryMutationResult = NonNullable<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsSummary>>>
    export type PostReportsApiV3WorkspaceWorkspaceIdProjectsSummaryMutationBody = DtoProjectUsersRequest
    export type PostReportsApiV3WorkspaceWorkspaceIdProjectsSummaryMutationError = string | string

    /**
 * @summary List project users
 */
export const usePostReportsApiV3WorkspaceWorkspaceIdProjectsSummary = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsSummary>>, TError,{workspaceId: number;data: DtoProjectUsersRequest}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsSummary>>,
        TError,
        {workspaceId: number;data: DtoProjectUsersRequest},
        TContext
      > => {

      const mutationOptions = getPostReportsApiV3WorkspaceWorkspaceIdProjectsSummaryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns project's summary.
 * @summary Load project summary
 */
export const postReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummary = (
    workspaceId: number,
    projectId: number,
    baseRangePost: BaseRangePost,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<TotalsReportData>(
      {url: `/reports/api/v3/workspace/${workspaceId}/projects/${projectId}/summary`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: baseRangePost, signal
    },
      options);
    }
  


export const getPostReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummaryMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummary>>, TError,{workspaceId: number;projectId: number;data: BaseRangePost}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummary>>, TError,{workspaceId: number;projectId: number;data: BaseRangePost}, TContext> => {

const mutationKey = ['postReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummary'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummary>>, {workspaceId: number;projectId: number;data: BaseRangePost}> = (props) => {
          const {workspaceId,projectId,data} = props ?? {};

          return  postReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummary(workspaceId,projectId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummaryMutationResult = NonNullable<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummary>>>
    export type PostReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummaryMutationBody = BaseRangePost
    export type PostReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummaryMutationError = string | string | string | string

    /**
 * @summary Load project summary
 */
export const usePostReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummary = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummary>>, TError,{workspaceId: number;projectId: number;data: BaseRangePost}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummary>>,
        TError,
        {workspaceId: number;projectId: number;data: BaseRangePost},
        TContext
      > => {

      const mutationOptions = getPostReportsApiV3WorkspaceWorkspaceIdProjectsProjectIdSummaryMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Returns time entries for summary report according to the given filters.
 * @summary Search time entries
 */
export const postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntries = (
    workspaceId: number,
    summaryReportPost: SummaryReportPost,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/reports/api/v3/workspace/${workspaceId}/summary/time_entries`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: summaryReportPost, signal
    },
      options);
    }
  


export const getPostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntries>>, TError,{workspaceId: number;data: SummaryReportPost}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntries>>, TError,{workspaceId: number;data: SummaryReportPost}, TContext> => {

const mutationKey = ['postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntries'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntries>>, {workspaceId: number;data: SummaryReportPost}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntries(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesMutationResult = NonNullable<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntries>>>
    export type PostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesMutationBody = SummaryReportPost
    export type PostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesMutationError = string | string | string | string

    /**
 * @summary Search time entries
 */
export const usePostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntries = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntries>>, TError,{workspaceId: number;data: SummaryReportPost}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntries>>,
        TError,
        {workspaceId: number;data: SummaryReportPost},
        TContext
      > => {

      const mutationOptions = getPostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Downloads summary report in pdf format.
 * @summary Export summary report
 */
export const postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdf = (
    workspaceId: number,
    summaryExportPDFPost: SummaryExportPDFPost,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/reports/api/v3/workspace/${workspaceId}/summary/time_entries.pdf`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: summaryExportPDFPost, signal
    },
      options);
    }
  


export const getPostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdfMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdf>>, TError,{workspaceId: number;data: SummaryExportPDFPost}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdf>>, TError,{workspaceId: number;data: SummaryExportPDFPost}, TContext> => {

const mutationKey = ['postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdf'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdf>>, {workspaceId: number;data: SummaryExportPDFPost}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdf(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdfMutationResult = NonNullable<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdf>>>
    export type PostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdfMutationBody = SummaryExportPDFPost
    export type PostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdfMutationError = string | string | string | string

    /**
 * @summary Export summary report
 */
export const usePostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdf = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdf>>, TError,{workspaceId: number;data: SummaryExportPDFPost}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdf>>,
        TError,
        {workspaceId: number;data: SummaryExportPDFPost},
        TContext
      > => {

      const mutationOptions = getPostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesPdfMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Downloads summary report in the specified in the specified format: csv or xlsx.
 * @summary Export summary report
 */
export const postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtension = (
    workspaceId: number,
    extension: string,
    summaryExportPost: SummaryExportPost,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/reports/api/v3/workspace/${workspaceId}/summary/time_entries.${extension}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: summaryExportPost, signal
    },
      options);
    }
  


export const getPostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtensionMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtension>>, TError,{workspaceId: number;extension: string;data: SummaryExportPost}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtension>>, TError,{workspaceId: number;extension: string;data: SummaryExportPost}, TContext> => {

const mutationKey = ['postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtension'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtension>>, {workspaceId: number;extension: string;data: SummaryExportPost}> = (props) => {
          const {workspaceId,extension,data} = props ?? {};

          return  postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtension(workspaceId,extension,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtensionMutationResult = NonNullable<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtension>>>
    export type PostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtensionMutationBody = SummaryExportPost
    export type PostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtensionMutationError = string | string | string | string

    /**
 * @summary Export summary report
 */
export const usePostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtension = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtension>>, TError,{workspaceId: number;extension: string;data: SummaryExportPost}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtension>>,
        TError,
        {workspaceId: number;extension: string;data: SummaryExportPost},
        TContext
      > => {

      const mutationOptions = getPostReportsApiV3WorkspaceWorkspaceIdSummaryTimeEntriesExtensionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    