// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetWorkspaceTagParams,
  ModelsTag,
  TagsPayload
} from './togglAPI.schemas';

import { togglAxios } from '../mutators/toggl';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * List Workspace tags.
 * @summary Tags
 */
export const getWorkspaceTag = (
    workspaceId: number,
    params?: GetWorkspaceTagParams,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsTag[]>(
      {url: `/workspaces/${workspaceId}/tags`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetWorkspaceTagQueryKey = (workspaceId?: number,
    params?: GetWorkspaceTagParams,) => {
    return [
    `/workspaces/${workspaceId}/tags`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetWorkspaceTagQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspaceTag>>, TError = string | string>(workspaceId: number,
    params?: GetWorkspaceTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTag>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspaceTagQueryKey(workspaceId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspaceTag>>> = ({ signal }) => getWorkspaceTag(workspaceId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTag>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWorkspaceTagQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceTag>>>
export type GetWorkspaceTagQueryError = string | string


export function useGetWorkspaceTag<TData = Awaited<ReturnType<typeof getWorkspaceTag>>, TError = string | string>(
 workspaceId: number,
    params: undefined |  GetWorkspaceTagParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTag>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceTag>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceTag>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceTag<TData = Awaited<ReturnType<typeof getWorkspaceTag>>, TError = string | string>(
 workspaceId: number,
    params?: GetWorkspaceTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTag>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceTag>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceTag>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceTag<TData = Awaited<ReturnType<typeof getWorkspaceTag>>, TError = string | string>(
 workspaceId: number,
    params?: GetWorkspaceTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTag>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Tags
 */

export function useGetWorkspaceTag<TData = Awaited<ReturnType<typeof getWorkspaceTag>>, TError = string | string>(
 workspaceId: number,
    params?: GetWorkspaceTagParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceTag>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWorkspaceTagQueryOptions(workspaceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Create workspace tags.
 * @summary Create tag
 */
export const postWorkspaceTag = (
    workspaceId: number,
    tagsPayload: TagsPayload,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsTag[]>(
      {url: `/workspaces/${workspaceId}/tags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: tagsPayload, signal
    },
      options);
    }
  


export const getPostWorkspaceTagMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceTag>>, TError,{workspaceId: number;data: TagsPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceTag>>, TError,{workspaceId: number;data: TagsPayload}, TContext> => {

const mutationKey = ['postWorkspaceTag'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkspaceTag>>, {workspaceId: number;data: TagsPayload}> = (props) => {
          const {workspaceId,data} = props ?? {};

          return  postWorkspaceTag(workspaceId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWorkspaceTagMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkspaceTag>>>
    export type PostWorkspaceTagMutationBody = TagsPayload
    export type PostWorkspaceTagMutationError = string | string | string

    /**
 * @summary Create tag
 */
export const usePostWorkspaceTag = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceTag>>, TError,{workspaceId: number;data: TagsPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkspaceTag>>,
        TError,
        {workspaceId: number;data: TagsPayload},
        TContext
      > => {

      const mutationOptions = getPostWorkspaceTagMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Patch will not be executed if there are errors with some records.
 * @summary Bulk delete tags
 */
export const patchWorkspaceTags = (
    workspaceId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<string>(
      {url: `/workspaces/${workspaceId}/tags`, method: 'PATCH'
    },
      options);
    }
  


export const getPatchWorkspaceTagsMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchWorkspaceTags>>, TError,{workspaceId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof patchWorkspaceTags>>, TError,{workspaceId: number}, TContext> => {

const mutationKey = ['patchWorkspaceTags'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchWorkspaceTags>>, {workspaceId: number}> = (props) => {
          const {workspaceId} = props ?? {};

          return  patchWorkspaceTags(workspaceId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchWorkspaceTagsMutationResult = NonNullable<Awaited<ReturnType<typeof patchWorkspaceTags>>>
    
    export type PatchWorkspaceTagsMutationError = string | string | string

    /**
 * @summary Bulk delete tags
 */
export const usePatchWorkspaceTags = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchWorkspaceTags>>, TError,{workspaceId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchWorkspaceTags>>,
        TError,
        {workspaceId: number},
        TContext
      > => {

      const mutationOptions = getPatchWorkspaceTagsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Update workspace tags.
 * @summary Update tag
 */
export const putWorkspaceTag = (
    workspaceId: number,
    tagId: number,
    tagsPayload: TagsPayload,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<ModelsTag[]>(
      {url: `/workspaces/${workspaceId}/tags/${tagId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: tagsPayload
    },
      options);
    }
  


export const getPutWorkspaceTagMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceTag>>, TError,{workspaceId: number;tagId: number;data: TagsPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceTag>>, TError,{workspaceId: number;tagId: number;data: TagsPayload}, TContext> => {

const mutationKey = ['putWorkspaceTag'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putWorkspaceTag>>, {workspaceId: number;tagId: number;data: TagsPayload}> = (props) => {
          const {workspaceId,tagId,data} = props ?? {};

          return  putWorkspaceTag(workspaceId,tagId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutWorkspaceTagMutationResult = NonNullable<Awaited<ReturnType<typeof putWorkspaceTag>>>
    export type PutWorkspaceTagMutationBody = TagsPayload
    export type PutWorkspaceTagMutationError = string | string | string | string

    /**
 * @summary Update tag
 */
export const usePutWorkspaceTag = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putWorkspaceTag>>, TError,{workspaceId: number;tagId: number;data: TagsPayload}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putWorkspaceTag>>,
        TError,
        {workspaceId: number;tagId: number;data: TagsPayload},
        TContext
      > => {

      const mutationOptions = getPutWorkspaceTagMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete workspace tags.
 * @summary Delete tag
 */
export const deleteWorkspaceTag = (
    workspaceId: number,
    tagId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<string>(
      {url: `/workspaces/${workspaceId}/tags/${tagId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteWorkspaceTagMutationOptions = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceTag>>, TError,{workspaceId: number;tagId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceTag>>, TError,{workspaceId: number;tagId: number}, TContext> => {

const mutationKey = ['deleteWorkspaceTag'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkspaceTag>>, {workspaceId: number;tagId: number}> = (props) => {
          const {workspaceId,tagId} = props ?? {};

          return  deleteWorkspaceTag(workspaceId,tagId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkspaceTagMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspaceTag>>>
    
    export type DeleteWorkspaceTagMutationError = string | string | string | string

    /**
 * @summary Delete tag
 */
export const useDeleteWorkspaceTag = <TError = string | string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceTag>>, TError,{workspaceId: number;tagId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWorkspaceTag>>,
        TError,
        {workspaceId: number;tagId: number},
        TContext
      > => {

      const mutationOptions = getDeleteWorkspaceTagMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    