// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetUsersTimeEntriesBody,
  ModelsTimeEntrySearchResult
} from './togglAPI.schemas.js';

import { togglAxios } from '../mutators/toggl.js';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Returns result of time_entries search
 * @summary Time entry data
 */
export const getUsersTimeEntries = (
    userId: number,
    getUsersTimeEntriesBody: GetUsersTimeEntriesBody,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`start`, getUsersTimeEntriesBody.start)
formUrlEncoded.append(`end`, getUsersTimeEntriesBody.end)
if(getUsersTimeEntriesBody.description !== undefined) {
 formUrlEncoded.append(`description`, getUsersTimeEntriesBody.description)
 }
if(getUsersTimeEntriesBody.project_name !== undefined) {
 formUrlEncoded.append(`project_name`, getUsersTimeEntriesBody.project_name)
 }
if(getUsersTimeEntriesBody.client_name !== undefined) {
 formUrlEncoded.append(`client_name`, getUsersTimeEntriesBody.client_name)
 }
if(getUsersTimeEntriesBody.user_agent !== undefined) {
 formUrlEncoded.append(`user_agent`, getUsersTimeEntriesBody.user_agent)
 }
if(getUsersTimeEntriesBody.deleted !== undefined) {
 formUrlEncoded.append(`deleted`, getUsersTimeEntriesBody.deleted.toString())
 }
if(getUsersTimeEntriesBody.deleted_start !== undefined) {
 formUrlEncoded.append(`deleted_start`, getUsersTimeEntriesBody.deleted_start)
 }
if(getUsersTimeEntriesBody.deleted_end !== undefined) {
 formUrlEncoded.append(`deleted_end`, getUsersTimeEntriesBody.deleted_end)
 }
if(getUsersTimeEntriesBody.partial_search !== undefined) {
 formUrlEncoded.append(`partial_search`, getUsersTimeEntriesBody.partial_search.toString())
 }
if(getUsersTimeEntriesBody.page !== undefined) {
 formUrlEncoded.append(`page`, getUsersTimeEntriesBody.page.toString())
 }
if(getUsersTimeEntriesBody.per_page !== undefined) {
 formUrlEncoded.append(`per_page`, getUsersTimeEntriesBody.per_page.toString())
 }
if(getUsersTimeEntriesBody.sort_field !== undefined) {
 formUrlEncoded.append(`sort_field`, getUsersTimeEntriesBody.sort_field)
 }
if(getUsersTimeEntriesBody.sort_order !== undefined) {
 formUrlEncoded.append(`sort_order`, getUsersTimeEntriesBody.sort_order)
 }

      return togglAxios<ModelsTimeEntrySearchResult>(
      {url: `/users/${userId}/time_entries`, method: 'GET',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', }, signal
    },
      options);
    }
  



export const getGetUsersTimeEntriesQueryKey = (userId?: number,
    getUsersTimeEntriesBody?: GetUsersTimeEntriesBody,) => {
    return [
    `/users/${userId}/time_entries`, getUsersTimeEntriesBody
    ] as const;
    }

    
export const getGetUsersTimeEntriesQueryOptions = <TData = Awaited<ReturnType<typeof getUsersTimeEntries>>, TError = void>(userId: number,
    getUsersTimeEntriesBody: GetUsersTimeEntriesBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersTimeEntries>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersTimeEntriesQueryKey(userId,getUsersTimeEntriesBody);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersTimeEntries>>> = ({ signal }) => getUsersTimeEntries(userId,getUsersTimeEntriesBody, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersTimeEntries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetUsersTimeEntriesQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersTimeEntries>>>
export type GetUsersTimeEntriesQueryError = void


export function useGetUsersTimeEntries<TData = Awaited<ReturnType<typeof getUsersTimeEntries>>, TError = void>(
 userId: number,
    getUsersTimeEntriesBody: GetUsersTimeEntriesBody, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersTimeEntries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersTimeEntries>>,
          TError,
          Awaited<ReturnType<typeof getUsersTimeEntries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetUsersTimeEntries<TData = Awaited<ReturnType<typeof getUsersTimeEntries>>, TError = void>(
 userId: number,
    getUsersTimeEntriesBody: GetUsersTimeEntriesBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersTimeEntries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersTimeEntries>>,
          TError,
          Awaited<ReturnType<typeof getUsersTimeEntries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetUsersTimeEntries<TData = Awaited<ReturnType<typeof getUsersTimeEntries>>, TError = void>(
 userId: number,
    getUsersTimeEntriesBody: GetUsersTimeEntriesBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersTimeEntries>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Time entry data
 */

export function useGetUsersTimeEntries<TData = Awaited<ReturnType<typeof getUsersTimeEntries>>, TError = void>(
 userId: number,
    getUsersTimeEntriesBody: GetUsersTimeEntriesBody, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersTimeEntries>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetUsersTimeEntriesQueryOptions(userId,getUsersTimeEntriesBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



