// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  WebAggregationsGenerationRequest
} from './togglAPI.schemas';

import { togglAxios } from '../mutators/toggl';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Regenerates aggregations for a given set of workspace IDs. The type of aggregations to be regenerated will either be project-total-time or planed-task-total-time.
 * @summary Regenerates aggregations for a given set of workspace IDs.
 */
export const generateAggregations = (
    webAggregationsGenerationRequest: WebAggregationsGenerationRequest,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<string>(
      {url: `/warehouse/aggregations/generate`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: webAggregationsGenerationRequest, signal
    },
      options);
    }
  


export const getGenerateAggregationsMutationOptions = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateAggregations>>, TError,{data: WebAggregationsGenerationRequest}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof generateAggregations>>, TError,{data: WebAggregationsGenerationRequest}, TContext> => {

const mutationKey = ['generateAggregations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof generateAggregations>>, {data: WebAggregationsGenerationRequest}> = (props) => {
          const {data} = props ?? {};

          return  generateAggregations(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GenerateAggregationsMutationResult = NonNullable<Awaited<ReturnType<typeof generateAggregations>>>
    export type GenerateAggregationsMutationBody = WebAggregationsGenerationRequest
    export type GenerateAggregationsMutationError = string | string

    /**
 * @summary Regenerates aggregations for a given set of workspace IDs.
 */
export const useGenerateAggregations = <TError = string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof generateAggregations>>, TError,{data: WebAggregationsGenerationRequest}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof generateAggregations>>,
        TError,
        {data: WebAggregationsGenerationRequest},
        TContext
      > => {

      const mutationOptions = getGenerateAggregationsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    