// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Toggl API
 * Public Toggl API.
Note:
We use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.
In our case it will be `base64(user_name:api_token)`.
 * OpenAPI spec version: 9
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ModelsLogo
} from './togglAPI.schemas.js';

import { togglAxios } from '../mutators/toggl.js';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get the logo for a given workspace.
 * @summary Get workspace logo
 */
export const getWorkspaceLogo = (
    workspaceId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsLogo>(
      {url: `/workspaces/${workspaceId}/logo`, method: 'GET', signal
    },
      options);
    }
  



export const getGetWorkspaceLogoQueryKey = (workspaceId?: number,) => {
    return [
    `/workspaces/${workspaceId}/logo`
    ] as const;
    }

    
export const getGetWorkspaceLogoQueryOptions = <TData = Awaited<ReturnType<typeof getWorkspaceLogo>>, TError = string | string | string>(workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceLogo>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWorkspaceLogoQueryKey(workspaceId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWorkspaceLogo>>> = ({ signal }) => getWorkspaceLogo(workspaceId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(workspaceId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceLogo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetWorkspaceLogoQueryResult = NonNullable<Awaited<ReturnType<typeof getWorkspaceLogo>>>
export type GetWorkspaceLogoQueryError = string | string | string


export function useGetWorkspaceLogo<TData = Awaited<ReturnType<typeof getWorkspaceLogo>>, TError = string | string | string>(
 workspaceId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceLogo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceLogo>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceLogo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceLogo<TData = Awaited<ReturnType<typeof getWorkspaceLogo>>, TError = string | string | string>(
 workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceLogo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWorkspaceLogo>>,
          TError,
          Awaited<ReturnType<typeof getWorkspaceLogo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetWorkspaceLogo<TData = Awaited<ReturnType<typeof getWorkspaceLogo>>, TError = string | string | string>(
 workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceLogo>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Get workspace logo
 */

export function useGetWorkspaceLogo<TData = Awaited<ReturnType<typeof getWorkspaceLogo>>, TError = string | string | string>(
 workspaceId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWorkspaceLogo>>, TError, TData>>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetWorkspaceLogoQueryOptions(workspaceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Post the logo for a given workspace.
 * @summary Post workspace logo
 */
export const postWorkspaceLogo = (
    workspaceId: number,
 options?: SecondParameter<typeof togglAxios>,signal?: AbortSignal
) => {
      
      
      return togglAxios<ModelsLogo>(
      {url: `/workspaces/${workspaceId}/logo`, method: 'POST', signal
    },
      options);
    }
  


export const getPostWorkspaceLogoMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceLogo>>, TError,{workspaceId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceLogo>>, TError,{workspaceId: number}, TContext> => {

const mutationKey = ['postWorkspaceLogo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postWorkspaceLogo>>, {workspaceId: number}> = (props) => {
          const {workspaceId} = props ?? {};

          return  postWorkspaceLogo(workspaceId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostWorkspaceLogoMutationResult = NonNullable<Awaited<ReturnType<typeof postWorkspaceLogo>>>
    
    export type PostWorkspaceLogoMutationError = string | string | string

    /**
 * @summary Post workspace logo
 */
export const usePostWorkspaceLogo = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postWorkspaceLogo>>, TError,{workspaceId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postWorkspaceLogo>>,
        TError,
        {workspaceId: number},
        TContext
      > => {

      const mutationOptions = getPostWorkspaceLogoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete the logo for a given workspace.
 * @summary Delete workspace logo
 */
export const deleteWorkspaceLogo = (
    workspaceId: number,
 options?: SecondParameter<typeof togglAxios>,) => {
      
      
      return togglAxios<ModelsLogo>(
      {url: `/workspaces/${workspaceId}/logo`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteWorkspaceLogoMutationOptions = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceLogo>>, TError,{workspaceId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceLogo>>, TError,{workspaceId: number}, TContext> => {

const mutationKey = ['deleteWorkspaceLogo'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteWorkspaceLogo>>, {workspaceId: number}> = (props) => {
          const {workspaceId} = props ?? {};

          return  deleteWorkspaceLogo(workspaceId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteWorkspaceLogoMutationResult = NonNullable<Awaited<ReturnType<typeof deleteWorkspaceLogo>>>
    
    export type DeleteWorkspaceLogoMutationError = string | string | string

    /**
 * @summary Delete workspace logo
 */
export const useDeleteWorkspaceLogo = <TError = string | string | string,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteWorkspaceLogo>>, TError,{workspaceId: number}, TContext>, request?: SecondParameter<typeof togglAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteWorkspaceLogo>>,
        TError,
        {workspaceId: number},
        TContext
      > => {

      const mutationOptions = getDeleteWorkspaceLogoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    