// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Redmine API
 * Unofficial OpenAPI specification for the Redmine API, tested against Redmine 6.1
 * OpenAPI spec version: 1.7.0+redmine6.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateIssueRelation201,
  CreateIssueRelationBody,
  Errors,
  GetIssueRelation200,
  GetIssueRelations200
} from './redmineAPI.schemas';

import { redmineAxios } from '../mutators/redmine';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List issue relations
 */
export const getIssueRelations = (
    issueId: number,
    format: 'json' | 'xml',
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<GetIssueRelations200>(
      {url: `/issues/${issueId}/relations.${format}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetIssueRelationsQueryKey = (issueId?: number,
    format?: 'json' | 'xml',) => {
    return [
    `/issues/${issueId}/relations.${format}`
    ] as const;
    }

    
export const getGetIssueRelationsQueryOptions = <TData = Awaited<ReturnType<typeof getIssueRelations>>, TError = void>(issueId: number,
    format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueRelations>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIssueRelationsQueryKey(issueId,format);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIssueRelations>>> = ({ signal }) => getIssueRelations(issueId,format, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(issueId && format), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIssueRelations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIssueRelationsQueryResult = NonNullable<Awaited<ReturnType<typeof getIssueRelations>>>
export type GetIssueRelationsQueryError = void


export function useGetIssueRelations<TData = Awaited<ReturnType<typeof getIssueRelations>>, TError = void>(
 issueId: number,
    format: 'json' | 'xml', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueRelations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssueRelations>>,
          TError,
          Awaited<ReturnType<typeof getIssueRelations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIssueRelations<TData = Awaited<ReturnType<typeof getIssueRelations>>, TError = void>(
 issueId: number,
    format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueRelations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssueRelations>>,
          TError,
          Awaited<ReturnType<typeof getIssueRelations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIssueRelations<TData = Awaited<ReturnType<typeof getIssueRelations>>, TError = void>(
 issueId: number,
    format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueRelations>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List issue relations
 */

export function useGetIssueRelations<TData = Awaited<ReturnType<typeof getIssueRelations>>, TError = void>(
 issueId: number,
    format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueRelations>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIssueRelationsQueryOptions(issueId,format,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create issue relation
 */
export const createIssueRelation = (
    issueId: number,
    format: 'json' | 'xml',
    createIssueRelationBody: CreateIssueRelationBody,
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<CreateIssueRelation201>(
      {url: `/issues/${issueId}/relations.${format}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createIssueRelationBody, signal
    },
      options);
    }
  


export const getCreateIssueRelationMutationOptions = <TError = void | Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIssueRelation>>, TError,{issueId: number;format: 'json' | 'xml';data: CreateIssueRelationBody}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof createIssueRelation>>, TError,{issueId: number;format: 'json' | 'xml';data: CreateIssueRelationBody}, TContext> => {

const mutationKey = ['createIssueRelation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createIssueRelation>>, {issueId: number;format: 'json' | 'xml';data: CreateIssueRelationBody}> = (props) => {
          const {issueId,format,data} = props ?? {};

          return  createIssueRelation(issueId,format,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateIssueRelationMutationResult = NonNullable<Awaited<ReturnType<typeof createIssueRelation>>>
    export type CreateIssueRelationMutationBody = CreateIssueRelationBody
    export type CreateIssueRelationMutationError = void | Errors

    /**
 * @summary Create issue relation
 */
export const useCreateIssueRelation = <TError = void | Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createIssueRelation>>, TError,{issueId: number;format: 'json' | 'xml';data: CreateIssueRelationBody}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createIssueRelation>>,
        TError,
        {issueId: number;format: 'json' | 'xml';data: CreateIssueRelationBody},
        TContext
      > => {

      const mutationOptions = getCreateIssueRelationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Show issue relation
 */
export const getIssueRelation = (
    issueRelationId: number,
    format: 'json' | 'xml',
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<GetIssueRelation200>(
      {url: `/relations/${issueRelationId}.${format}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetIssueRelationQueryKey = (issueRelationId?: number,
    format?: 'json' | 'xml',) => {
    return [
    `/relations/${issueRelationId}.${format}`
    ] as const;
    }

    
export const getGetIssueRelationQueryOptions = <TData = Awaited<ReturnType<typeof getIssueRelation>>, TError = void>(issueRelationId: number,
    format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueRelation>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIssueRelationQueryKey(issueRelationId,format);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIssueRelation>>> = ({ signal }) => getIssueRelation(issueRelationId,format, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(issueRelationId && format), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIssueRelation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIssueRelationQueryResult = NonNullable<Awaited<ReturnType<typeof getIssueRelation>>>
export type GetIssueRelationQueryError = void


export function useGetIssueRelation<TData = Awaited<ReturnType<typeof getIssueRelation>>, TError = void>(
 issueRelationId: number,
    format: 'json' | 'xml', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueRelation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssueRelation>>,
          TError,
          Awaited<ReturnType<typeof getIssueRelation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIssueRelation<TData = Awaited<ReturnType<typeof getIssueRelation>>, TError = void>(
 issueRelationId: number,
    format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueRelation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssueRelation>>,
          TError,
          Awaited<ReturnType<typeof getIssueRelation>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIssueRelation<TData = Awaited<ReturnType<typeof getIssueRelation>>, TError = void>(
 issueRelationId: number,
    format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueRelation>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Show issue relation
 */

export function useGetIssueRelation<TData = Awaited<ReturnType<typeof getIssueRelation>>, TError = void>(
 issueRelationId: number,
    format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueRelation>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIssueRelationQueryOptions(issueRelationId,format,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Delete issue relation
 */
export const deleteIssueRelation = (
    issueRelationId: number,
    format: 'json' | 'xml',
 options?: SecondParameter<typeof redmineAxios>,) => {
      
      
      return redmineAxios<void>(
      {url: `/relations/${issueRelationId}.${format}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteIssueRelationMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIssueRelation>>, TError,{issueRelationId: number;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteIssueRelation>>, TError,{issueRelationId: number;format: 'json' | 'xml'}, TContext> => {

const mutationKey = ['deleteIssueRelation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteIssueRelation>>, {issueRelationId: number;format: 'json' | 'xml'}> = (props) => {
          const {issueRelationId,format} = props ?? {};

          return  deleteIssueRelation(issueRelationId,format,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteIssueRelationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteIssueRelation>>>
    
    export type DeleteIssueRelationMutationError = void

    /**
 * @summary Delete issue relation
 */
export const useDeleteIssueRelation = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIssueRelation>>, TError,{issueRelationId: number;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteIssueRelation>>,
        TError,
        {issueRelationId: number;format: 'json' | 'xml'},
        TContext
      > => {

      const mutationOptions = getDeleteIssueRelationMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    