// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Redmine API
 * Unofficial OpenAPI specification for the Redmine API, tested against Redmine 6.1
 * OpenAPI spec version: 1.7.0+redmine6.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetIssueStatuses200
} from './redmineAPI.schemas';

import { redmineAxios } from '../mutators/redmine';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List issue statuses
 */
export const getIssueStatuses = (
    format: 'json' | 'xml',
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<GetIssueStatuses200>(
      {url: `/issue_statuses.${format}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetIssueStatusesQueryKey = (format?: 'json' | 'xml',) => {
    return [
    `/issue_statuses.${format}`
    ] as const;
    }

    
export const getGetIssueStatusesQueryOptions = <TData = Awaited<ReturnType<typeof getIssueStatuses>>, TError = unknown>(format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueStatuses>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIssueStatusesQueryKey(format);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIssueStatuses>>> = ({ signal }) => getIssueStatuses(format, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(format), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIssueStatuses>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetIssueStatusesQueryResult = NonNullable<Awaited<ReturnType<typeof getIssueStatuses>>>
export type GetIssueStatusesQueryError = unknown


export function useGetIssueStatuses<TData = Awaited<ReturnType<typeof getIssueStatuses>>, TError = unknown>(
 format: 'json' | 'xml', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueStatuses>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssueStatuses>>,
          TError,
          Awaited<ReturnType<typeof getIssueStatuses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIssueStatuses<TData = Awaited<ReturnType<typeof getIssueStatuses>>, TError = unknown>(
 format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueStatuses>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIssueStatuses>>,
          TError,
          Awaited<ReturnType<typeof getIssueStatuses>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetIssueStatuses<TData = Awaited<ReturnType<typeof getIssueStatuses>>, TError = unknown>(
 format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueStatuses>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List issue statuses
 */

export function useGetIssueStatuses<TData = Awaited<ReturnType<typeof getIssueStatuses>>, TError = unknown>(
 format: 'json' | 'xml', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIssueStatuses>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetIssueStatusesQueryOptions(format,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



