// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Redmine API
 * Unofficial OpenAPI specification for the Redmine API, tested against Redmine 6.1
 * OpenAPI spec version: 1.7.0+redmine6.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProject201,
  CreateProjectBody,
  Errors,
  GetProject200,
  GetProjectParams,
  GetProjects200,
  GetProjectsParams,
  UpdateProjectBody
} from './redmineAPI.schemas.js';

import { redmineAxios } from '../mutators/redmine.js';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List projects
 */
export const getProjects = (
    format: 'json' | 'xml',
    params?: GetProjectsParams,
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<GetProjects200>(
      {url: `/projects.${format}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetProjectsQueryKey = (format?: 'json' | 'xml',
    params?: GetProjectsParams,) => {
    return [
    `/projects.${format}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetProjectsQueryOptions = <TData = Awaited<ReturnType<typeof getProjects>>, TError = unknown>(format: 'json' | 'xml',
    params?: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectsQueryKey(format,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjects>>> = ({ signal }) => getProjects(format,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(format), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getProjects>>>
export type GetProjectsQueryError = unknown


export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = unknown>(
 format: 'json' | 'xml',
    params: undefined |  GetProjectsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List projects
 */

export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetProjectsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetProjectsQueryOptions(format,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create project
 */
export const createProject = (
    format: 'json' | 'xml',
    createProjectBody: CreateProjectBody,
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<CreateProject201>(
      {url: `/projects.${format}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createProjectBody, signal
    },
      options);
    }
  


export const getCreateProjectMutationOptions = <TError = Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{format: 'json' | 'xml';data: CreateProjectBody}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{format: 'json' | 'xml';data: CreateProjectBody}, TContext> => {

const mutationKey = ['createProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createProject>>, {format: 'json' | 'xml';data: CreateProjectBody}> = (props) => {
          const {format,data} = props ?? {};

          return  createProject(format,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof createProject>>>
    export type CreateProjectMutationBody = CreateProjectBody
    export type CreateProjectMutationError = Errors

    /**
 * @summary Create project
 */
export const useCreateProject = <TError = Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createProject>>, TError,{format: 'json' | 'xml';data: CreateProjectBody}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createProject>>,
        TError,
        {format: 'json' | 'xml';data: CreateProjectBody},
        TContext
      > => {

      const mutationOptions = getCreateProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Show project
 */
export const getProject = (
    projectId: number | string,
    format: 'json' | 'xml',
    params?: GetProjectParams,
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<GetProject200>(
      {url: `/projects/${projectId}.${format}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetProjectQueryKey = (projectId?: number | string,
    format?: 'json' | 'xml',
    params?: GetProjectParams,) => {
    return [
    `/projects/${projectId}.${format}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetProjectQueryOptions = <TData = Awaited<ReturnType<typeof getProject>>, TError = void>(projectId: number | string,
    format: 'json' | 'xml',
    params?: GetProjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectQueryKey(projectId,format,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProject>>> = ({ signal }) => getProject(projectId,format,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(projectId && format), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetProjectQueryResult = NonNullable<Awaited<ReturnType<typeof getProject>>>
export type GetProjectQueryError = void


export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = void>(
 projectId: number | string,
    format: 'json' | 'xml',
    params: undefined |  GetProjectParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = void>(
 projectId: number | string,
    format: 'json' | 'xml',
    params?: GetProjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = void>(
 projectId: number | string,
    format: 'json' | 'xml',
    params?: GetProjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Show project
 */

export function useGetProject<TData = Awaited<ReturnType<typeof getProject>>, TError = void>(
 projectId: number | string,
    format: 'json' | 'xml',
    params?: GetProjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetProjectQueryOptions(projectId,format,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update project
 */
export const updateProject = (
    projectId: number | string,
    format: 'json' | 'xml',
    updateProjectBody: UpdateProjectBody,
 options?: SecondParameter<typeof redmineAxios>,) => {
      
      
      return redmineAxios<void>(
      {url: `/projects/${projectId}.${format}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateProjectBody
    },
      options);
    }
  


export const getUpdateProjectMutationOptions = <TError = void | Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: number | string;format: 'json' | 'xml';data: UpdateProjectBody}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: number | string;format: 'json' | 'xml';data: UpdateProjectBody}, TContext> => {

const mutationKey = ['updateProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProject>>, {projectId: number | string;format: 'json' | 'xml';data: UpdateProjectBody}> = (props) => {
          const {projectId,format,data} = props ?? {};

          return  updateProject(projectId,format,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateProjectMutationResult = NonNullable<Awaited<ReturnType<typeof updateProject>>>
    export type UpdateProjectMutationBody = UpdateProjectBody
    export type UpdateProjectMutationError = void | Errors

    /**
 * @summary Update project
 */
export const useUpdateProject = <TError = void | Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProject>>, TError,{projectId: number | string;format: 'json' | 'xml';data: UpdateProjectBody}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateProject>>,
        TError,
        {projectId: number | string;format: 'json' | 'xml';data: UpdateProjectBody},
        TContext
      > => {

      const mutationOptions = getUpdateProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete project
 */
export const deleteProject = (
    projectId: number | string,
    format: 'json' | 'xml',
 options?: SecondParameter<typeof redmineAxios>,) => {
      
      
      return redmineAxios<void>(
      {url: `/projects/${projectId}.${format}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteProjectMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext> => {

const mutationKey = ['deleteProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteProject>>, {projectId: number | string;format: 'json' | 'xml'}> = (props) => {
          const {projectId,format} = props ?? {};

          return  deleteProject(projectId,format,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteProjectMutationResult = NonNullable<Awaited<ReturnType<typeof deleteProject>>>
    
    export type DeleteProjectMutationError = void

    /**
 * @summary Delete project
 */
export const useDeleteProject = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteProject>>,
        TError,
        {projectId: number | string;format: 'json' | 'xml'},
        TContext
      > => {

      const mutationOptions = getDeleteProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Archive project
 */
export const archiveProject = (
    projectId: number | string,
    format: 'json' | 'xml',
 options?: SecondParameter<typeof redmineAxios>,) => {
      
      
      return redmineAxios<void>(
      {url: `/projects/${projectId}/archive.${format}`, method: 'PUT'
    },
      options);
    }
  


export const getArchiveProjectMutationOptions = <TError = void | Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof archiveProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext> => {

const mutationKey = ['archiveProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof archiveProject>>, {projectId: number | string;format: 'json' | 'xml'}> = (props) => {
          const {projectId,format} = props ?? {};

          return  archiveProject(projectId,format,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ArchiveProjectMutationResult = NonNullable<Awaited<ReturnType<typeof archiveProject>>>
    
    export type ArchiveProjectMutationError = void | Errors

    /**
 * @summary Archive project
 */
export const useArchiveProject = <TError = void | Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof archiveProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof archiveProject>>,
        TError,
        {projectId: number | string;format: 'json' | 'xml'},
        TContext
      > => {

      const mutationOptions = getArchiveProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Unarchive project
 */
export const unarchiveProject = (
    projectId: number | string,
    format: 'json' | 'xml',
 options?: SecondParameter<typeof redmineAxios>,) => {
      
      
      return redmineAxios<void>(
      {url: `/projects/${projectId}/unarchive.${format}`, method: 'PUT'
    },
      options);
    }
  


export const getUnarchiveProjectMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unarchiveProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof unarchiveProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext> => {

const mutationKey = ['unarchiveProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof unarchiveProject>>, {projectId: number | string;format: 'json' | 'xml'}> = (props) => {
          const {projectId,format} = props ?? {};

          return  unarchiveProject(projectId,format,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UnarchiveProjectMutationResult = NonNullable<Awaited<ReturnType<typeof unarchiveProject>>>
    
    export type UnarchiveProjectMutationError = void

    /**
 * @summary Unarchive project
 */
export const useUnarchiveProject = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof unarchiveProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof unarchiveProject>>,
        TError,
        {projectId: number | string;format: 'json' | 'xml'},
        TContext
      > => {

      const mutationOptions = getUnarchiveProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Undocumented: This operation is not listed in the official documentation.
 * @summary Close project
 */
export const closeProject = (
    projectId: number | string,
    format: 'json' | 'xml',
 options?: SecondParameter<typeof redmineAxios>,) => {
      
      
      return redmineAxios<void>(
      {url: `/projects/${projectId}/close.${format}`, method: 'PUT'
    },
      options);
    }
  


export const getCloseProjectMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof closeProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext> => {

const mutationKey = ['closeProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof closeProject>>, {projectId: number | string;format: 'json' | 'xml'}> = (props) => {
          const {projectId,format} = props ?? {};

          return  closeProject(projectId,format,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CloseProjectMutationResult = NonNullable<Awaited<ReturnType<typeof closeProject>>>
    
    export type CloseProjectMutationError = void

    /**
 * @summary Close project
 */
export const useCloseProject = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof closeProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof closeProject>>,
        TError,
        {projectId: number | string;format: 'json' | 'xml'},
        TContext
      > => {

      const mutationOptions = getCloseProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Undocumented: This operation is not listed in the official documentation.
 * @summary Reopen project
 */
export const reopenProject = (
    projectId: number | string,
    format: 'json' | 'xml',
 options?: SecondParameter<typeof redmineAxios>,) => {
      
      
      return redmineAxios<void>(
      {url: `/projects/${projectId}/reopen.${format}`, method: 'PUT'
    },
      options);
    }
  


export const getReopenProjectMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reopenProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof reopenProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext> => {

const mutationKey = ['reopenProject'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reopenProject>>, {projectId: number | string;format: 'json' | 'xml'}> = (props) => {
          const {projectId,format} = props ?? {};

          return  reopenProject(projectId,format,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReopenProjectMutationResult = NonNullable<Awaited<ReturnType<typeof reopenProject>>>
    
    export type ReopenProjectMutationError = void

    /**
 * @summary Reopen project
 */
export const useReopenProject = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reopenProject>>, TError,{projectId: number | string;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reopenProject>>,
        TError,
        {projectId: number | string;format: 'json' | 'xml'},
        TContext
      > => {

      const mutationOptions = getReopenProjectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    