// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Redmine API
 * Unofficial OpenAPI specification for the Redmine API, tested against Redmine 6.1
 * OpenAPI spec version: 1.7.0+redmine6.1
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetQueries200,
  GetQueriesParams
} from './redmineAPI.schemas';

import { redmineAxios } from '../mutators/redmine';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List queries
 */
export const getQueries = (
    format: 'json' | 'xml',
    params?: GetQueriesParams,
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<GetQueries200>(
      {url: `/queries.${format}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetQueriesQueryKey = (format?: 'json' | 'xml',
    params?: GetQueriesParams,) => {
    return [
    `/queries.${format}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetQueriesQueryOptions = <TData = Awaited<ReturnType<typeof getQueries>>, TError = unknown>(format: 'json' | 'xml',
    params?: GetQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQueries>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueriesQueryKey(format,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueries>>> = ({ signal }) => getQueries(format,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(format), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQueries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetQueriesQueryResult = NonNullable<Awaited<ReturnType<typeof getQueries>>>
export type GetQueriesQueryError = unknown


export function useGetQueries<TData = Awaited<ReturnType<typeof getQueries>>, TError = unknown>(
 format: 'json' | 'xml',
    params: undefined |  GetQueriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQueries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQueries>>,
          TError,
          Awaited<ReturnType<typeof getQueries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetQueries<TData = Awaited<ReturnType<typeof getQueries>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQueries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQueries>>,
          TError,
          Awaited<ReturnType<typeof getQueries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetQueries<TData = Awaited<ReturnType<typeof getQueries>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQueries>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List queries
 */

export function useGetQueries<TData = Awaited<ReturnType<typeof getQueries>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQueries>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetQueriesQueryOptions(format,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



