// @ts-nocheck
/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Redmine API
 * Unofficial OpenAPI specification for the Redmine API, tested against Redmine 6.1
 * OpenAPI spec version: 1.7.0+redmine6.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateUser201,
  CreateUserBody,
  Errors,
  GetCurrentUser200,
  GetCurrentUserParams,
  GetUser200,
  GetUserParams,
  GetUsers200,
  GetUsersParams,
  UpdateUserBody
} from './redmineAPI.schemas.js';

import { redmineAxios } from '../mutators/redmine.js';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary List users
 */
export const getUsers = (
    format: 'json' | 'xml',
    params?: GetUsersParams,
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<GetUsers200>(
      {url: `/users.${format}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetUsersQueryKey = (format?: 'json' | 'xml',
    params?: GetUsersParams,) => {
    return [
    `/users.${format}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(format: 'json' | 'xml',
    params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersQueryKey(format,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) => getUsers(format,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(format), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUsersQueryError = unknown


export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 format: 'json' | 'xml',
    params: undefined |  GetUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary List users
 */

export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetUsersQueryOptions(format,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create user
 */
export const createUser = (
    format: 'json' | 'xml',
    createUserBody: CreateUserBody,
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<CreateUser201>(
      {url: `/users.${format}`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createUserBody, signal
    },
      options);
    }
  


export const getCreateUserMutationOptions = <TError = Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{format: 'json' | 'xml';data: CreateUserBody}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{format: 'json' | 'xml';data: CreateUserBody}, TContext> => {

const mutationKey = ['createUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, {format: 'json' | 'xml';data: CreateUserBody}> = (props) => {
          const {format,data} = props ?? {};

          return  createUser(format,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
    export type CreateUserMutationBody = CreateUserBody
    export type CreateUserMutationError = Errors

    /**
 * @summary Create user
 */
export const useCreateUser = <TError = Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{format: 'json' | 'xml';data: CreateUserBody}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {format: 'json' | 'xml';data: CreateUserBody},
        TContext
      > => {

      const mutationOptions = getCreateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Show user
 */
export const getUser = (
    userId: number,
    format: 'json' | 'xml',
    params?: GetUserParams,
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<GetUser200>(
      {url: `/users/${userId}.${format}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetUserQueryKey = (userId?: number,
    format?: 'json' | 'xml',
    params?: GetUserParams,) => {
    return [
    `/users/${userId}.${format}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetUserQueryOptions = <TData = Awaited<ReturnType<typeof getUser>>, TError = void>(userId: number,
    format: 'json' | 'xml',
    params?: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserQueryKey(userId,format,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUser>>> = ({ signal }) => getUser(userId,format,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId && format), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetUserQueryResult = NonNullable<Awaited<ReturnType<typeof getUser>>>
export type GetUserQueryError = void


export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = void>(
 userId: number,
    format: 'json' | 'xml',
    params: undefined |  GetUserParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = void>(
 userId: number,
    format: 'json' | 'xml',
    params?: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUser>>,
          TError,
          Awaited<ReturnType<typeof getUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = void>(
 userId: number,
    format: 'json' | 'xml',
    params?: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Show user
 */

export function useGetUser<TData = Awaited<ReturnType<typeof getUser>>, TError = void>(
 userId: number,
    format: 'json' | 'xml',
    params?: GetUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUser>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetUserQueryOptions(userId,format,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Update user
 */
export const updateUser = (
    userId: number,
    format: 'json' | 'xml',
    updateUserBody: UpdateUserBody,
 options?: SecondParameter<typeof redmineAxios>,) => {
      
      
      return redmineAxios<void>(
      {url: `/users/${userId}.${format}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateUserBody
    },
      options);
    }
  


export const getUpdateUserMutationOptions = <TError = void | Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{userId: number;format: 'json' | 'xml';data: UpdateUserBody}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{userId: number;format: 'json' | 'xml';data: UpdateUserBody}, TContext> => {

const mutationKey = ['updateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {userId: number;format: 'json' | 'xml';data: UpdateUserBody}> = (props) => {
          const {userId,format,data} = props ?? {};

          return  updateUser(userId,format,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = UpdateUserBody
    export type UpdateUserMutationError = void | Errors

    /**
 * @summary Update user
 */
export const useUpdateUser = <TError = void | Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{userId: number;format: 'json' | 'xml';data: UpdateUserBody}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {userId: number;format: 'json' | 'xml';data: UpdateUserBody},
        TContext
      > => {

      const mutationOptions = getUpdateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Delete user
 */
export const deleteUser = (
    userId: number,
    format: 'json' | 'xml',
 options?: SecondParameter<typeof redmineAxios>,) => {
      
      
      return redmineAxios<void>(
      {url: `/users/${userId}.${format}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteUserMutationOptions = <TError = void | Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{userId: number;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{userId: number;format: 'json' | 'xml'}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {userId: number;format: 'json' | 'xml'}> = (props) => {
          const {userId,format} = props ?? {};

          return  deleteUser(userId,format,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    
    export type DeleteUserMutationError = void | Errors

    /**
 * @summary Delete user
 */
export const useDeleteUser = <TError = void | Errors,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{userId: number;format: 'json' | 'xml'}, TContext>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {userId: number;format: 'json' | 'xml'},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Show current user
 */
export const getCurrentUser = (
    format: 'json' | 'xml',
    params?: GetCurrentUserParams,
 options?: SecondParameter<typeof redmineAxios>,signal?: AbortSignal
) => {
      
      
      return redmineAxios<GetCurrentUser200>(
      {url: `/users/current.${format}`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetCurrentUserQueryKey = (format?: 'json' | 'xml',
    params?: GetCurrentUserParams,) => {
    return [
    `/users/current.${format}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCurrentUserQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(format: 'json' | 'xml',
    params?: GetCurrentUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserQueryKey(format,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUser>>> = ({ signal }) => getCurrentUser(format,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(format), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type GetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUser>>>
export type GetCurrentUserQueryError = unknown


export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
 format: 'json' | 'xml',
    params: undefined |  GetCurrentUserParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetCurrentUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetCurrentUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
/**
 * @summary Show current user
 */

export function useGetCurrentUser<TData = Awaited<ReturnType<typeof getCurrentUser>>, TError = unknown>(
 format: 'json' | 'xml',
    params?: GetCurrentUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUser>>, TError, TData>>, request?: SecondParameter<typeof redmineAxios>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getGetCurrentUserQueryOptions(format,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



